### ISSUE TITLE
Summarize Search.gov integration needs and break out into individual tickets

### ISSUE THREAD

**Issue by christophermather** [18F/guides#106]
### A description of the work
Based on our [conversation with Search.gov](https://docs.google.com/document/d/1s6xDeUMMwHk4uYR3jAtXbNOPsuRcYDjSFnp__pEkyhk/edit#heading=h.4eyd3iu66m8l), let's clearly articulate what our next steps are for implementation of search on the replatformed guides.

Some questions:

- When does search get activated? 
- What implementation quirks do we need to stay mindful of? 
- What kind of coordination do we need to maintain with the Search.gov team?

### Point of contact on this issue
Who can we follow-up with if we have questions?

### Reproduction steps (if necessary)
Be as specific as possible

**Billable?**

- [ ] Yes
- [ ] No
If yes, tock code:

**Skills needed**
- [ ] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria
- [ ] We have a shared understanding of how we'll roll out Search when replatforming guides
- [ ] We have an epic issue for Search that lists out tasks and any dependencies between them
- [ ] We have clear issues tasked out in the backlog

### Tasks
- [ ]

**Comment by christophermather** [comment]
Note: let's make an epic to house all Search implementation issues

**Comment by alexbielen** [comment]
^ Added something epic-related to the acceptance criteria
