### ISSUE TITLE
Create a branch of the Guides repo for information architecture prototyping

### ISSUE THREAD

**Issue by christophermather** [18F/guides#128]
### A description of the work

We'd like to prototype some new information architecture. In order to do that, we need to make a branch of the guides repo for us to play around in, independent of the ongoing replatforming work.

Blocks #129 

### Point of contact on this issue
Who can we follow-up with if we have questions?
@christophermather 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**
- [ ] Any human
- [ ] Design
- [ ] Content
- [x] Engineering
- [ ] Acquisition
- [x] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [x] Yes
- [ ] No

### How much time do you anticipate this work taking?
<1 increment

### Acceptance Criteria

1. [x] We have a branch that we can use as a sandbox for testing out a new information architecture
- URL: https://github.com/18F/guides/tree/kbighorse-information-architecture-prototyping
3. [x] Sandbox is available to stakeholders (only) over the Internet
- URL: https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/kbighorse-information-architecture-prototyping/
4. [x] Owner of #129 is able to modify the content to create new section
5. [x] Design is able to access published site for testing purposes
(last 2 ACs are out-of-scope here: cloud.gov Pages handles access)

**Comment by christophermather** [comment]
@kbighorse - I've flagged this work to @igorkorenfeld and @eric-gade, who are both working on Guides replatforming. 

As of right now, this issues is pretty light and lacks technical context. I could use some help elaborating so we know exactly what we're doing and that the language we're using is accurate.

**Comment by juliaklindpaintner** [comment]
Pausing on this effort due to some changes in priority.

**Comment by christophermather** [comment]
Closing as done, since we abandoned this path.
