### ISSUE TITLE
[EPIC] Incremental UX improvements to existing Guides

### ISSUE THREAD

**Issue by christophermather** [18F/guides#142]
### A description of the work

We have a [set of recommendations](https://docs.google.com/document/d/1qWGc7K4hm3941vbAOD8quLRn3AWzbyQBtSV_GqhHAxg/edit) for incremental improvements to the UX of the existing Guides. These recommendations should be implemented _as we replatform_ or _after we replatform_. These improvements do not need to be implemented on the current Guides sites.

These recommendations fall into several categories:

**Now**
#143 
#144 
#145 

**Next**
Issues generated from other recommendations from Aviva's document

**Later**
Another round of UX research/recommendations
Issues generated from these new rec's

### Point of contact on this issue

@christophermather

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

```[tasklist]
### Tasks
- [ ] https://github.com/18F/guides/issues/143
- [ ] https://github.com/18F/guides/issues/144
- [ ] https://github.com/18F/guides/issues/145
```

**Comment by christophermather** [comment]
Closing this as done, since the two remaining items on this task list are part of #213.
