### ISSUE TITLE
Migrate the Accessibility guide to the new setup

### ISSUE THREAD

**Issue by christophermather** [18F/guides#159]
### A description of the work
We will migrate the accessibility guide to the new consolidated, replatformed guides setup.
  
As with the migration of all guides, we will also be using this opportunity to refine the [guide/checklist for migrating individual guides](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit?usp=sharing).

### Point of contact on this issue
@christophermather 

### Reproduction steps (if necessary)
Most of the steps we expect to follow can be found in the [draft individual migration guide document](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit?usp=sharing). From a high level, these include:

**Soft release**
- [x] Make sure that all pre-migration issues have been completed and that the specific guide is prepared (tests are passing, there are no `TODO` links left over
- [x] Confirm DNS records are up-to-date for the OLD guide domain
- [x] Remove redirects from the new URL to the old guides (ie, stop `guides.18f.gov/[guide-name]` from redirecting to `[guide-name].18f.gov`)
- [x] Add the new guide in the Search.gov admin panel [instructions](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit#heading=h.x2mu289iagkf)

**Hard release**
- [x] Permanently redirect old guide URLs to the new guide (ie, `[guide-name].18f.gov/etc/etc2/` redirects to `guides.18f.gov/[guide-name]/etc/etc2/`)

**Post release**
- [x] Monitor analytics for the new site for some specified period of time
- [x] Update 18f.gsa.gov website to use new guides link
- [x] Turn on automatic reviewer tagging for guide
- [x] Update the [working migration doc](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit?usp=sharing) with any refinements of the process, to make future migrations easier
  
#### Other resources ####
* [pages-redirects](https://github.com/cloud-gov/pages-redirects) repository where the routing changes will be made (see the migration doc)

**Billable?**

- [ ] Yes
- [X] No
If yes, tock code:

**Skills needed**

- [ ] Any human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [ ] No

How much time do you anticipate this work taking?
The changes should be straightforward, but the merge and deploy of reroutes will take an unspecified amount of time, as it relies upon Cloud-gov's internal processes.

### Acceptance Criteria

- [ ] `guides.18f.gov/accessibility/` points to the new, live, replatformed Accessibility guide
- [ ] Analytics is able to show incoming data for the new Accessibility guide after some specified period of time
- [ ] We have a refined [migration doc](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit?usp=sharing) available for future migrations

**Comment by echappen** [comment]
Done!
