### ISSUE TITLE
Visually compare migrated guides against existing guides

### ISSUE THREAD

**Issue by christophermather** [18F/guides#167]
### A description of the work

This is part of step 1 in the [18F guide to migrating a guide](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit#heading=h.yx1bkn2xsrw7). This task follows #157.

As a final step before starting migration steps, we need to visually compare migrated guides against existing guides to do a final validation pass that they are ready to migrate.

### Ready for review
_Based on completed tasks from #157_

- ~De-risking (@a-chappelear )~
- ~Engineering Hiring (@a-chappelear )~
- ~Accessibility (@qmanderson1)~
- ~Content (@a-chappelear)~
- ~Brand (@a-chappelear)~
- ~Engineering (@a-chappelear)~
- ~Product (@a-chappelear)~
-  ~User Experience (@a-chappelear)~

### Point of contact on this issue

@christophermather

### Our evaluation rubric
Parity not perfection!

We want to make sure that we're not _losing_ any functionality. If we come across any errors or problems that exist on both sites, we should log them in our [tracker spreadsheet](https://docs.google.com/spreadsheets/d/1fjmS-XVRWYtDFpO71HuTlI6sb7z1NLt92atRPHGqrRE/edit#gid=0). We will add them to the backlog and address post-migration.

### Reproduction steps

This will involve a manual click-through of sites. Meaning:

1. Pull up the replatformed guide URL in one window 
2. Pull up the corresponding existing guide URL in another
3. Scan each page for visual similarity/uniformity
4. Make note of any (significant) discrepancies. You can add these discrepancies to [this tracker spreadsheet](https://docs.google.com/spreadsheets/d/1fjmS-XVRWYtDFpO71HuTlI6sb7z1NLt92atRPHGqrRE/edit#gid=0).
5. If no discrepancies, mark that guide as complete in task list below
6. If discrepancies, review w/ @christophermather and add issues to the backlog

### Skills Needed

- [x] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Engineering Hiring
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [x] Yes
- [ ] No

### Acceptance Criteria

- [x] All replatformed guides have been checked against the existing guides 
- [x] Guides that are ready are given the greenlight
- [x] Guides that have any discrepancies have been flagged as blocked and discrepancies have been turned into issues in the backlog
```[tasklist]
### Tasks
- [x] Accessibility guide visual comparison complete
- [x] Content guide visual comparison complete
- [x] De-risking guide visual comparison complete
- [x] Engineering guide visual comparison complete
- [x] Product guide visual comparison complete
- [x] User Experience guide visual comparison complete
- [x] Brand guide visual comparison complete
- [x] Engineering Hiring guide visual comparison complete
```

**Comment by christophermather** [comment]
Confirming that the visual comparisons are done, we've logged discrepancies, verified that certain design changes were intentional, flagged a couple items for follow-up, and created issues for any items that are blocking migration (specifically, #203 and #205).
