### ISSUE TITLE
Adjust migration strategy based on Cloud.gov feedback

### ISSUE THREAD

**Issue by christophermather** [18F/guides#168]
### A description of the work

Based on this [Slack conversation](https://gsa-tts.slack.com/archives/C03LHEFGSF7/p1699998532990339?thread_ts=1699990913.672339&cid=C03LHEFGSF7) with Cloud.gov, we need to determine what - if any - new steps we need to add to our launch list/migration strategy for each guide that we roll out.

### Point of contact on this issue

@christophermather

### Reproduction steps (if necessary)

- [ ] Discuss recommendations
- [ ] Decide if we need to adjust strategy or add steps
- [ ] Add those steps to both GitHub issues and our [Guide to migrating a guide](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit#heading=h.yx1bkn2xsrw7)

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria

- [ ] Cloud.gov conversation has been reviewed and discussed
- [ ] New steps for guide launch strategy - if any - have been established
- [ ] Those new steps have been added to our [Guide to migrating a guide](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit#heading=h.yx1bkn2xsrw7)
- [ ] Those steps have been added to GitHub guide migration issues

**Comment by echappen** [comment]
After confirming with Andrew Burnes from Cloud, I've added a [Step 4](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit#heading=h.9yuttxmn3nic) to the migration guide
