### ISSUE TITLE
Create step-by-step for accessing + monitoring Guides analytics

### ISSUE THREAD

**Issue by christophermather** [18F/guides#204]
### A description of the work

One of our migration steps is to monitor analytics for one week following migration. I'm not sure we have the institutional knowledge for how to do this. 

It would be good for us to 1) gain the correct access, 2) learn how to locate the correct analytics and 3) document the whole process.

### Point of contact on this issue

@christophermather

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria

- [ ] We can access Google Analytics for 18F Guides
- [ ] We know how to drill into the appropriate views to monitor individual guides post-migration
- [ ] We know what to look for
- [ ] We've documented the above

**Comment by christophermather** [comment]
Two steps that we've taken so far:

1. Reached out to dap@gsa.gov and requested access to the dashboard for guides.18f.gov
2. Reached out to [#g-analytics](https://gsa-tts.slack.com/archives/C02AK9NKP) and requested access to Google Analytics for guides.18.gov

I still haven't gone through documentation, but unclear if I (or Eleni) have the appropriate access to be able to view our analytics.

**Comment by christophermather** [comment]
OK, [this documentation](https://docs.google.com/document/d/1P4lLMVKEUjTtl2sroXt6izN8cAPr2Vlqie5gnuhe1K0/edit) is complete. A condensed version of the instructions also appears in the [guide to migrating a guide](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit).
