### ISSUE TITLE
Header link icon breaks to second line at a certain title lengths

### ISSUE THREAD

**Issue by christophermather** [18F/guides#207]
### A description of the work

When an h2 header title is of a particular length, the link icon breaks to a second line on its own. We need to decide 1) if we think this is a problem, 2) if we can think of a solution and 3) if it's worth solving given the effort.

Note that this affects titles of particular lengths - long, but not so long that the title text breaks to a second line - and titles of particular length in certain viewports (mobile, tablet).

Some examples of this happening:

Content guide > Our style > Voice and tone
<img width="628" alt="image" src="https://github.com/18F/guides/assets/97245800/3432a0f0-2e6f-4745-ac2a-9360c74e5fbe">

Brand > Templates > Google Slides presentation templates
<img width="632" alt="image" src="https://github.com/18F/guides/assets/97245800/260937ea-4fd3-4628-858c-e8e2108e9264">

Brand > Principles > Convince with soundness not loudness
<img width="619" alt="image" src="https://github.com/18F/guides/assets/97245800/09cadd3f-669b-40b2-a852-842f5d3d884b">

### Point of contact on this issue

@christophermather

### Skills Needed

- [ ] Any Human
- [X] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria

- [ ] Decide whether this is a problem (design)
- [ ] If so, suggest a solution (engineering)
- [ ] Determine whether juice is worth the squeeze (design/engineering/product)

**Comment by adunkman** [comment]
See [this Slack thread](https://gsa-tts.slack.com/archives/C02CZB4G5/p1709318965555159) for suggestions on how to approach.

**Comment by beepdotgov** [comment]
Just me here, but I'd be inclined to see if `text-wrap: balance` helps address the issue. (Fully agree with the Slack thread that `text-wrap: pretty` would be ideal, but `balance`'s browser support is a bit better.)

Happy to look into this whenever it's ready to be prioritized.

**Comment by bpdesigns** [comment]
@adunkman I recommend prioritizing this while we have people with front end skills on TLC
