### ISSUE TITLE
Develop strategy for minimizing gap between soft and hard release of guides

### ISSUE THREAD

**Issue by christophermather** [18F/guides#214]
### A description of the work

Based on our current [step-by-step](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit) for migrating the guides, there is a potential gap between soft release and hard release.

### Background and definitions

**Definitions**
- **Soft release:** Here, we're defining "soft release" as the moment we remove redirects from the new URL to the old guides (ie, stop `guides.18f.gov/[guide-name]` from redirecting to `[guide-name].18f.gov`)
- **Hard release:** "Hard release" is when we permanently redirect old guide URLs to the new guide (ie, `[guide-name].18f.gov/etc/etc2/` redirects to `guides.18f.gov/[guide-name]/etc/etc2/`)

**Background:** We have control over the steps in soft release. However, we need to coordinate with Cloud.gov to make the changes in hard release.

**Why this matters:** Since we control one side and not the other, it's possible for a gap to exist between these two changes, and for that gap to be large. 

**What we want to do:** We want to make that gap as small as possible without over-burdening Cloud or slowing ourselves down.

**What we need to know:** What kind of response time can we expect from Cloud? Could/should we schedule a (weekly) time to release? 

**Hypothesis:** In order to keep guides releases moving forward and to minimize the gap between soft and hard release, we should schedule a regular release time with Cloud that their team can commit to. We will batch as many guides as is feasible + safe and hand over to Cloud at those prescheduled times.

### Point of contact on this issue

@christophermather

### Reproduction steps (if necessary)

- [ ] Meet w/ Cloud.gov to discuss strategy and scheduling
- [ ] Draft a plan and discuss w/ engineers

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria

- [ ] We have a strategy (and possibly schedule) with Cloud.gov team to more seamlessly complete the hard release of each guide
- [ ] The gap between soft release and hard release of the guides is small (< 48 hrs) and predictable
- [ ] The pace of our guides releases is not impeded by coordination w/ Cloud

**Comment by christophermather** [comment]
@echappen and @christophermather are attending today's Cloud.gov office hours to discuss.
