### ISSUE TITLE
[EPIC]: Migrate Methods site

### ISSUE THREAD

**Issue by echappen** [18F/guides#224]
Migrate Methods site content from Jekyll into 11ty, so that we can reduce maintenance costs and leverage shared resources with the rest of the guides. 

```[tasklist]
### Tasks
- [ ] https://github.com/18F/guides/issues/225
- [ ] https://github.com/18F/guides/issues/226
- [ ] https://github.com/18F/guides/issues/227
- [ ] https://github.com/18F/guides/issues/228
- [ ] https://github.com/18F/guides/issues/229
- [ ] https://github.com/18F/guides/issues/230
- [ ] https://github.com/18F/guides/issues/231
- [ ] https://github.com/18F/guides/issues/232
- [ ] https://github.com/18F/guides/issues/233
- [ ] https://github.com/18F/guides/issues/234
- [ ] https://github.com/18F/guides/issues/235
- [ ] https://github.com/18F/guides/issues/352
- [ ] https://github.com/18F/guides/issues/236
- [ ] https://github.com/18F/guides/issues/357
- [ ] https://github.com/18F/guides/issues/237
```

**Comment by echappen** [comment]
@cantsin @juliaklindpaintner I wanted to give a status update to this epic before I leave TLC:
- All items from design review are resolved. There are [~3 minor design suggestions](https://github.com/18F/guides/issues?q=is%3Aissue+is%3Aopen+label%3A%22methods+design+review%22) that came out of review that shouldn’t need to block the launch. (All issues from review have the label “methods design review”.)
- @jasnakai is currently doing an accessibility review of the new site. Any issues that come out of that will be labeled “a11y”. I’ll leave it to TLC to determine whether those issues should be resolved before or after launch. 
- After a11y review, the site will be good to launch. I don’t know who will be available to [go through the steps](https://docs.google.com/document/d/19b1Y2pSyw1EjXzc2XmL-qXqQCfqiVQLkypOO8zJKUKw/edit#heading=h.yx1bkn2xsrw7), but I don’t think the two sites should linger around in tandem for too long. I’m happy to launch it myself or guide anyone else in the process.
