### ISSUE TITLE
Port over all remaining content for Methods site

### ISSUE THREAD

**Issue by echappen** [18F/guides#234]
### A description of the work

Part of Epic #224 

- This includes all card and header/footer content
- Jekyll frontmatter from old site may need to be adjusted for Eleventy
- Make all buttons and links functional

### Point of contact on this issue

Eleni Chappen

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

1-2 days

### Acceptance Criteria

- New methods site has the same content as old site
- New methods pages have the same URL paths as old site
- All buttons and links work
- pages are checked for 404's against old sitemap

## Checklist (please add if you discover more), remove if we're not moving them

- [x] Discovery cards
- [x] Decide cards
- [x] Make cards
- [x] Validate cards
- [x] Fundamentals cards
- [x] ~/archive/bodystorming~ archived
- [x] /interview-checklist
- [x] /interview-debrief
- [x] ~/participant-agreement-spanish~ use UX Guide version
- [x] ~/participant-agreement~ use UX Guide version
- [x] /usability-test-script
- [x] /service-blueprint-example
- [x] ~/rolling-issue-log~ awaiting decision on whether to keep this
- [x] /interview-script
- [x] /assets/downloads/18F-Method-Cards-Print-Instructions.pdf
- [x] /assets/downloads/18F-Method-Cards-Print-at-home.pdf
- [x] /assets/downloads/FEC-Sitemap.pdf

**Comment by echappen** [comment]
Finally completed in https://github.com/18F/guides/pull/353
