### ISSUE TITLE
Conduct Visual Reviews of Methods site

### ISSUE THREAD

**Issue by echappen** [18F/guides#236]
### A description of the work

Conduct a visual review of new site that ensures visual parity with the original methods site.

Since we have automated tests to check for broken links, manual checking for broken links is not necessary.

Use these builds for comparison:
[New site](https://federalist-8bc0b42c-5fd0-4ae8-9366-cd9c265a4446.sites.pages.cloud.gov/preview/18f/guides/eoc/design-review-template/methods/) 
[Old site](https://methods.18f.gov/)

Accessibility review will be done [separately](https://github.com/18F/guides/issues/357), but if any a11y issues affect design, note them.

#### Page assignment

- [x] Discover pages (including All Discover cards page) - @juliaklindpaintner 
- [x] Decide pages (including all Decide cards page) - @melchoyce 
- [x] Make pages (including all Make cards page) - @melchoyce 
- [x] Validate pages (including all Make cards page) - @melchoyce 
- [x] Fundamentals pages (including all Fundamentals cards page) - @melchoyce 
- [x] [About](https://methods.18f.gov/about/) - @juliaklindpaintner 
- [x] [Print the Methods](https://methods.18f.gov/print/) - @juliaklindpaintner 
- [x] [Service blueprint example](https://methods.18f.gov/service-blueprint-example/) - @melchoyce 
- [x] [Usability test script](https://methods.18f.gov/usability-test-script/) - @melchoyce 
- [x] [Interview Checklist](https://methods.18f.gov/interview-checklist/) - @melchoyce 
- [x] [Interview Debrief](https://methods.18f.gov/interview-debrief/) - @melchoyce 
- [x] [Interview Script](https://methods.18f.gov/interview-script/) - @melchoyce 

#### Known issues
1. The new site uses USWDS v3, and old site uses v2, so there will be some slight adjustments in font size and spacing. The whole repo uses the same USWDS version, so let's keep to the v3 defaults as much as possible. If there's something egregiously off, then we'll consider a USWDS override. 
2. Link icons don't show up for some headers because they're not created from Markdown. This is a known issue described in https://github.com/18F/guides/issues/274
3. There are some redundant pages with the UX guide, described in https://github.com/18F/guides/issues/356
4. Markdown checkboxes don't render by default in 11ty, described in https://github.com/18F/guides/issues/294

#### How to submit an issue

If you want to submit an issue, first check if there's an [existing issue](https://github.com/18F/guides/issues?q=is%3Aissue+is%3Aopen+) for it. If there's an existing issue, make sure it has the "methods design review" label.

If there's no issue, create a new issue using [this issue template](https://github.com/18F/guides/issues/new?assignees=octocat&labels=Initiative+2%2CGuides%2Cmethods+design+review&projects=18F%2F41&template=design-review.yml&title=%5BBug%5D%3A+) which should give it the label "methods design review" automatically.

Part of of Epic #224 

### Point of contact on this issue

Eleni Chappen

### Skills Needed

- [X] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

1-2 days

### Acceptance Criteria

- Ensure all items are prioritized for migration (fix before migration / fix after / won't fix)

**Comment by echappen** [comment]
Done: all issues are accounted for, labeled "methods design review"
