### ISSUE TITLE
Go through link audit and create new issues

### ISSUE THREAD

**Issue by christophermather** [18F/guides#249]
### A description of the work

Background: as part of completing https://github.com/18F/TLC-crew/issues/341, we did a [link audit](https://docs.google.com/spreadsheets/d/1T-J8gAfyuToa7Kzzi2KMAyLxaOJfi6mCW8q5b7ChWYA/edit) of the guides, looking for links that are both `external` and `non-federal`. Where those links appear, we need to ensure we are surfacing non-endorsement copy.

In order for this ticket to be complete, we may need to do all of the following:

- [x] Develop a solution/create a ticket to develop a solution for non-endorsement copy
- [x] Create tickets to apply solution wherever links that are both `external` and `non-federal` appear
- [x] Create tickets for any other miscellaneous issues noted in the audit

### Point of contact on this issue

@christophermather

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### How much time do you anticipate this work taking?

2 days

### Acceptance Criteria

- [ ] We have created an issue to develop a solution for non-endorsement copy (may involved design)
- [ ] We have created issues for all links flagged in the [link audit](https://docs.google.com/spreadsheets/d/1T-J8gAfyuToa7Kzzi2KMAyLxaOJfi6mCW8q5b7ChWYA/edit) 
- [ ] We have created issues for any miscellaneous tasks also flagged in the audit (404s, icons missing, etc.)

**Comment by christophermather** [comment]
Closing and moving this to done.

This issue generated two new issues:
- https://github.com/18F/guides/issues/348
- https://github.com/18F/guides/issues/347
