### ISSUE TITLE
Move lingering issues from old guides repos to new guide repo

### ISSUE THREAD

**Issue by christophermather** [18F/guides#250]
### A description of the work

Background: there are some lingering issues in the old guides repos. These should be moved over to the new Guides repo so that we can sort through, prioritize and/or eliminate.

This whole ticket may not be doable in this increment, but we should prioritize getting admin access and moving the issues over so that we don't forget about them.

### Guides

Guide | # of issues | Contact | Done?
-- | -- | -- | --
[Accessibility](https://github.com/18F/accessibility/issues) | 4 | @jasnakai | 🟢 
[Agile](https://github.com/18F/agile/issues) | 0 | @adunkman | 🟢
[Brand](https://github.com/18F/brand/issues) | 10 | @igorkorenfeld | 🟢 
[Content](https://github.com/18F/content-guide/issues) | 0 | @michelle-rago  | 🟢
[De-risking](https://github.com/18F/derisking-gov-tech/issues) | 5 | @adunkman | 🟢
[Engineering](https://github.com/18F/development-guide/issues) | 11 | @amymok | 🟢 
[Engineering Hiring](https://github.com/18F/eng-hiring/issues) | 8 | @amymok | 🟢 
[Product](https://github.com/18F/product-guide/issues) | 1 | @allisonnorman | 🟢
[User Experience](https://github.com/18F/ux-guide/issues) | 35 | @juliaklindpaintner | 🟢
[Methods](https://github.com/18F/methods/issues) | 25 | @MelissaBraxton |  
Total | 99 |   |  

### Point of contact on this issue

@christophermather

### Reproduction steps (if necessary)

- [x] Get admin access to old guides repos
- [x] Review issues
- [x] Move any that seem viable over to new guides repo

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### How much time do you anticipate this work taking?

1 week

### Acceptance Criteria

- [x] @christophermather has admin access to old guides repos
- [x] Issues from old guides repos have been moved over to new guides repo
- [x] The issues have been reviewed and prioritize (and some possibly deleted)

**Comment by christophermather** [comment]
Tracking these issues in [this spreadsheet](https://docs.google.com/spreadsheets/d/17t6p0OP5LWSvb9ORJ5pLarcgJmd-g_ilrSVwlyeCN4M/edit#gid=0).

Issues from old **Guides** repos have all been moved over to the consolidated Guides repos. They all have labels identifying their origin repos. Methods issues have not yet been moved.

The issues from Guides need a little bit of sorting and prioritizing. I think they should be sorted in two ways:

1. **Batch issues for code owner review.** Some - maybe most - issues should get a review from the old repos' code owners, especially old issues that may no longer be relevant. We're looking for validation that "yes, this issue is worth holding onto".
2. **Group like issues in epics.** These issues may span across different guides. They may be driving towards similar outcomes (improve accessibility, update IA) or simply be addressing similar needs (broken links, etc.).

**Comment by amymok** [comment]
Hi @christophermather.  Can you help me understand what I need to do here?  Do you want me to look thru all the engineering items and say yes or no to hold onto?  And where should I record that in the spreadsheet or else where?  Thank you!

**Comment by christophermather** [comment]
Hi @amymok! No action at the moment - apologies for the premature notification!

I'm going to organize some tasks in our backlog for your review in a separate issue that will have some instructions. Hoping to actually have something your way by end of day today.

Thanks for asking!

**Comment by christophermather** [comment]
This work is done. For more info, see https://github.com/18F/guides/issues/393
