### ISSUE TITLE
🟡 Review guide for broken/out-of-date links

### ISSUE THREAD

**Issue by kmori** [18F/guides#252]
**Background**
The 18F Product Guides has a large number of links out to other sources, both internal and external to 18F. The 18F Product Guide hasn't had maintenance or review of its content in the last couple years, which means some of the resources may be out-of-date and may also not follow current best practices. Because the links to resources are such a significant part of the guide in its current state, we should make sure that they're at least accurate, up-to-date, and clear.

As an 18F PM using the 18F product guide, the links and references should send me to the appropriate place and the descriptions should make it clear where I'm being sent to.

**Acceptance criteria _(we'll know we're done when…)_** 
- [x] We have compiled a list of all the links/resources in the product guide
- [x] We have [documented all links within the product guide](https://docs.google.com/spreadsheets/d/1pvlsZsOBgjl3dvE9OP5zcswd8fLtrRJPMxYhAyRC4LE/edit#gid=0)
  - Note: This document does not include links that link to another part of the product guide
- [x] We have documented which links are broken
- [x] We have documented which links we should consider updating (both URL and reference text)

**Comment by allisonnorman** [comment]
Related issue - #311. 

It seems like it's not worth the effort to make generalizable templates for all of these resources now given I expect we will iterate on guides and likely evolve our content as we roll out the doctrine. If this isn't the case and this guide will exist as it does for the mid/long term, we can revisit.
