### ISSUE TITLE
🟡 Align product guide with other product resources

### ISSUE THREAD

**Issue by kmori** [18F/guides#255]
**Background**
including[ TTS handbook page](https://handbook.tts.gsa.gov/18f/chapters/product/) and [Product Welcome Guide](https://docs.google.com/document/d/18YQtfLVb4klrZlUhKpZWYcDmM_PNKeYsWTPqMrcWcLE/edit#heading=h.c11ctoeqyd2s)

**Acceptance criteria _(we'll know we're done when…)_** 
- [x] make sure we are reconciling differences in favor of the practices we bring to our engagements, rather than generalizing our guide to match other, broader guides

**Tasks**
- [x] Review [ TTS handbook page](https://handbook.tts.gsa.gov/18f/chapters/product/), [Product Welcome Guide](https://docs.google.com/document/d/18YQtfLVb4klrZlUhKpZWYcDmM_PNKeYsWTPqMrcWcLE/edit#heading=h.c11ctoeqyd2s) and [18F Product Guide](https://guides.18f.gov/product/)
- [x] Document any inconsistencies 
- [x] Recommend updates to the 18F Product Guide
- [x] @allisonnorman review [if task involves content changes] 
- [x]  Accessibility review [if needed]
- [x]  Outreach approval [if needed]

**Comment by allisonnorman** [comment]
[Reviewing old issues] - This is a great idea but I'm not sure where guides are heading so will mark this as 🟡 while I await next information on how much to invest in the current state vs shifting towards a new doctrine-focused guide.

**Comment by bpdesigns** [comment]
@allisonnorman any update on if this is a relevant issue? Maybe good for an new person?

**Comment by allisonnorman** [comment]
Hi! Yeah, I think a lightweight reconciliation is a good call. I wouldn't spend too much time on it as I'm trying to figure out from LT how much more we should invest in the product guide or if we can shift focus to something more in line with upcoming doctrine work. Reconciling the two resources laid out in this issue with the product guide, and/or deciding not to include stuff from it entirely makes sense to me for a TLC issue for one of the new folks if they're up for it!

**Comment by bpdesigns** [comment]
@allisonnorman I updated the task list in this issue. Let me know if you have any questions or changes to it.

**Comment by c-collins** [comment]
I compared the docs mentioned and only minor changes were needed to the Product Welcome Guide after reviewing with @allisonnorman. My summary of findings and recommendations can be found here: https://docs.google.com/document/d/1ng_IZUlXrCXVIO3yZlFgLQB1G7hISImqFvN6QjgS2Jc/edit?usp=sharing

I also made an update to the TTS Onboarding Map per the recommendation: https://app.mural.co/t/gsa6/m/gsa6/1635521163000/f7f123a002c0fd265df0f6c9d1935282fd24b030?sender=uaddabf881f2b734b6ede9711

**Comment by bpdesigns** [comment]
Thanks @c-collins! LGTM
