### ISSUE TITLE
Add, organize and prioritize issues in backlog for continued Guides work in 2024

### ISSUE THREAD

**Issue by christophermather** [18F/guides#265]
### A description of the work

Background: we'd like to set up the TLC crew to continue some Guides improvement in the new year. These items can come from a few places, including:
- [TLC backlog](https://github.com/orgs/18F/projects/41)
- [old Guides repos](https://github.com/18F/guides/issues/250)
- these [UX recommendations](https://docs.google.com/document/d/1qWGc7K4hm3941vbAOD8quLRn3AWzbyQBtSV_GqhHAxg/edit#heading=h.5elu6thm6kvw)
- the [link audit](https://github.com/18F/guides/issues/249)

### Point of contact on this issue

@christophermather

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria

- [ ] We've generated as many issues as possible
- [ ] Where we haven't been able to generate issues, we've appropriately described how to generate issues from resources listed
- [ ] Issues are organized (in epics, possibly) and prioritize if possible
