### ISSUE TITLE
🟢 Create meta descriptions for the UX Guide pages

### ISSUE THREAD

**Issue by bpdesigns** [18F/guides#284]
```[tasklist]
### Tasks
- [x] Identify what pages to add meta descriptions for
- [x] Draft metadescriptions
- [x] Get codeowner approval of the meta descriptions
- [x] Add meta descriptions to the UX guide
```

**Comment by juliaklindpaintner** [comment]
See the completed work for the De-risking Guide as a reference here #461.

**Comment by allisonpress** [comment]
Drafting meta descriptions in [this spreadsheet](https://docs.google.com/spreadsheets/d/1oA7YoQaTRqg-xJPuzSOE4NpreQqaOtHmlkNarStRBZI/edit?usp=sharing)

**Comment by juliaklindpaintner** [comment]
@allisonpress These are great! I made one suggested edit, but otherwise good to implement! Let me know if you need help with next steps.
