### ISSUE TITLE
🔴 Making content consistent in the ux guide 

### ISSUE THREAD

**Issue by bpdesigns** [18F/guides#285]
**Background**
See this [thread](https://gsa-tts.slack.com/archives/C03LHEFGSF7/p1671139450856569) from Anne on content governance considerations.

- Consider if a glossary of terms is needed.
- Consider what language might have changed as preferred terms since the guide was published. 
 
**Acceptance criteria** 
- [ ] Contributors to the UX Guide understand what tone and voice they should write content from so readers understand who is the focus of the content
- [ ] Contributors have clarity on definition of common terms so readers of the guide have clarity about what is being discussed 

**Potential Tasks**
- [ ] Decide where reference documentation for the content tone and specific language choices should live. Ex, in a google doc or linked in the repo's wiki.
- [ ] Create reference documentation

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by juliaklindpaintner** [comment]
Closing this as I don't think it should be done in isolation for the UX Guide.
