### ISSUE TITLE
🟡 Linking content to the TTS Handbook

### ISSUE THREAD

**Issue by bpdesigns** [18F/guides#288]
**Background**
There are multiple sources of information across TTS public documented websites that reference approaches, methods and restrictions to design and research at GSA and in the Federal Government. 

**Acceptance criteria** 
- [ ] There is one source of truth between  these sites and are linked to other relevant references so that if someone changes a method or policy it is consistent across our documents

**Tasks**
- [ ] review the Design, Research and DEIA sections of the TTS Handbook for duplicative content and decide between the three sites where the content should live.
- [ ] update this information in 18F/ux-guide#395 of the Methods repo.

**Definition of done**
- [ ]  One of the POs has approved the change
- [ ]  Outreach approval (if needed)

**Comment by bpdesigns** [comment]
Just reviewed content and its not conflicting
