### ISSUE TITLE
🟢 Update UX Guide Resource page with current links

### ISSUE THREAD

**Issue by bpdesigns** [18F/guides#291]
**Background**
 The Resource page of the UX guide is outdated

**Acceptance criteria** 
- [ ] content should be up to date 
- [ ] content should be what is expected when looking for ux design research resources 

**Tasks**
- [ ] review the page for outdated content and links to outdated content
- [ ] update content to be current
- [ ] Ensure that we're referring to links in a way that's consistent w/ the methods (#588)
- [ ] remove content that is not specifically a ux design research resource

### Point of contact on this issue
You can reach out to @bpdesigns 

**Billable?**

- [ ] Yes
- [x] No
If yes, tock code:

**Skills needed**

- [x] Any human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
-  less than one weeks

**Definition of done**
- [ ]  @bpdesigns or @MelissaBraxton has approved the update

**Comment by dluetger** [comment]
Working on an audit sheet for this, but a few items as we go along.

1. In the spirit of "remove content that is not specifically a ux design research resource," to me this means everything from `General` onward at the bottom of this page would just be deleted. Maybe `Presentations` and `Additional Reading` stay. It's a lot of "directory" sort of stuff and I feel like that problem is closer to solved with the new guides and methods architecture and such.
2. Ballpark 75% of the links are pairs of a "public" version and a locked, 18F-only version, which sort of made me wonder who the primary audience of this page was. Every public link paired with a "VIP private" link feels like a little much and I'm wondering if anyone has an opinion on whether to limit the page to one or the other.

**Comment by dluetger** [comment]
Also, if we are very aggressive on removing content that's not _directly_ relevant, the stuff under `Collaboration` might go as well. Again that seems like more "helpful directory" style content

**Comment by dluetger** [comment]
Some conclusions so far based on the criteria:

content should be up to date

- Nothing is explicitly out of date or recommending incorrect or harmful information as far as I can tell
- For many internal links and public-facing "how to" pages, we should ask if that's still how we do things or if that particular doc is really being used by team members any more

content should be what is expected when looking for ux design research resources

- Every working link goes to where it says it goes
- Nothing is completely unexpected or irrelevant but I recommend removing the content under "Collaboration" and "General"
- Some of the Slack links reference out-of-date procedures or go to the default channel instead of the one indicated

review the page for outdated content and links to outdated content

- As above, nothing is explicitly out of date or recommending incorrect or harmful information as far as I can tell
- For many internal links and public-facing "how to" pages, we should ask if that's still how we do things or if that particular doc is really being used by team members any more
- For links to external pages or friends of the show, so far I haven't looked too deeply at how up-to-date it is or if it's being maintained, but it's all still there

update content to be current

- This seems like a much bigger task -- nothing is wildly incorrect but there is some internal questions we should ask about what's actually being used

Ensure that we're referring to links in a way that's consistent w/ the methods (#588)

- Need to check this still

remove content that is not specifically a ux design research resource

- Nothing is completely unexpected or irrelevant but I recommend removing the content under "Collaboration" and "General"
- "Tools"" seems very incomplete to the point where we might just want to axe it for now?"

**Comment by dluetger** [comment]
I think _minimum_ cleanup until we get opinions or info on if and when some of the resources are being used is to drop the "irrelevant" stuff and keep every other link that is working and expected.

**Comment by MelissaBraxton** [comment]
@juliaklindpaintner is the current UX Guide owner, I believe. But a few thoughts from me: 
- WRT to determining whether internal resources are up-to-date, I'd cross reference with the current 18F doctrine inventory, wherever that is. Maybe @juliaklindpaintner knows? 
- Similarly, I think the link to project resources folder may not be the best place to point folks. 
- Agree with getting rid of what's under "collaboration" 
- Under "general" The last 4 resources are UX specific and useful. Maybe we just remove the stuff above that and find a better/more descriptive header for the last 4? 

Agree that the link Q should be settled by having more clarity on the audience we want to larger (internal vs. external), but I think that should be part of a larger strategy re: the guides more generally.

**Comment by juliaklindpaintner** [comment]
Thanks for your work on this @dluetger and thanks for the tag and your thoughts @MelissaBraxton!

 > - WRT to determining whether internal resources are up-to-date, I'd cross reference with the current 18F doctrine inventory, wherever that is. Maybe @juliaklindpaintner knows?

There hasn't been much progress here for a number of reasons. There was an effort to gather feedback on this [inventory of resources](https://docs.google.com/spreadsheets/d/19AVzPbrrlaCYNyR2IYYQaZ_EHuqzBQrF2B5SPgMzph8/edit#gid=2139787878), which was [summarized in this document](https://docs.google.com/document/d/1bRiSBb6TWFdYycMHfjox84VNjRYR0zkSIEjwe1ni-F8/edit#heading=h.jmjn81mtfaop) by category, but I don't think it will provide any clear answers on whether the things we link to are still up to date. Makes me wonder if we could work on some of these docs as a Design crit activity...  

> - Similarly, I think the link to project resources folder may not be the best place to point folks.

Inasmuch as this still functions as an internal resource, I don't see an issue with linking to project resources, but perhaps we should change it to link to the [Airtable](https://airtable.com/shrZDkbAFlqkpxY8G)? 

 > - Agree with getting rid of what's under "collaboration"

Agree! Let's 🪓.

 > - Under "general" The last 4 resources are UX specific and useful. Maybe we just remove the stuff above that and find a better/more descriptive header for the last 4?

I agree with removing the first 2, but since the two from OPM are a pair, I'd keep both. They could be consolidated to one bullet point linking to both, though. The references link is the odd link out here; the rest are "Other government resources on UX research and design" or "Other government guides to UX"? 

> Agree that the link Q should be settled by having more clarity on the audience we want to larger (internal vs. external), but I think that should be part of a larger strategy re: the guides more generally.

Agree with this. I think it's beyond the scope of this ticket to clean that up, so I'd leave it alone for now. 

So, @dluetger, I'd say that to close out this ticket, you should just make the changes to the Collaboration and Additional reading sections and create a follow-on ticket that lists out specifically which documents need to be reviewed for accuracy/up-to-date-ness.

**Comment by dluetger** [comment]
Created [506](https://github.com/18F/guides/issues/506) as a followup

**Comment by juliaklindpaintner** [comment]
I think this one can be closed, right @dluetger?
