### ISSUE TITLE
🔴 Document UX Guide site architecture in wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/guides#292]
**Background**
Document the site architecture in the wiki to help folks working on the site get oriented and up-to-speed quickly. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] The site architecture is live on the wiki
- [ ]  An engineer unfamiliar with the project can understand the site architecture after viewing the wiki content

**Tasks**
- [ ] Draft architecture diagram
- [ ]  PO review [if task involves content changes] 
- [ ] Post architecture documentation to the wiki
- [ ]  Accessibility review

**Comment by juliaklindpaintner** [comment]
Closing this as there is no existing wiki for the new guides website yet and this should be considered holistically with the rest of the guides.
