### ISSUE TITLE
🟡 Include co-design approaches and resources in the UX guide

### ISSUE THREAD

**Issue by amandarkennedy** [18F/guides#293]
**Background**
This issue will help 18F better: "Know, share, use and evolve our best practices"

- We have not conducted co-design activities but want to move in that direction. 
- There is no current established practice on researching with communities at 18F. We need to document what GSA and TTS has put forward about this and how to operationalize within the 18F research practice through the 18F UX Guide. 
- We have already updated the **Plan** section of the UX guide with considerations for recruiting communities (see 18F/ux-guide#320). Now, we have an opportunity to expand on these emergent practices throughout the rest of the guide. This issue covers **co-design.**

**Acceptance criteria**
- [ ] Update the UX Guide [Do](https://ux-guide.18f.gov/research/do) section to include co-design approaches and resources
- [ ] Use the 18F Guides team [design principles](https://docs.google.com/document/d/1o8RIEwRFGXtxgO6g_NyI0STFH4LJ-2CF_Oc9dJq0sQ8/edit#) to help determine framing the content, and reference some of GSA's long-term goals in the [Equity Action Plan](https://www.gsa.gov/cdnstatic/GSAEquityPlan_EO13985_2022.pdf) as our North Star.

 **Tasks**

- [ ] Review relevant resources below.
- [ ] Create a doc with a definition of co-design and draft content about what it would look like to work in this way as well as barriers that need to be removed.
- [ ] Once reviewed update the content in github and tag @bpdesigns and @MelissaBraxton for review.
- [ ] Determine if there are any other subject matter experts who should be included in the review process, and name them here.
- [ ] Document any considerations/ideas for co-design showing up in the 18F Methods

**Relevant resources**
- [ ] [Methods and Guides design principles](https://docs.google.com/document/d/1o8RIEwRFGXtxgO6g_NyI0STFH4LJ-2CF_Oc9dJq0sQ8/edit#)
- [ ] [Equity Action Plan](https://www.gsa.gov/cdnstatic/GSAEquityPlan_EO13985_2022.pdf)
- [ ] [Considerations for engaging communities with respect](https://github.com/GSA-TTS/10x-Equity-centered-design-with-American-Indians-and-Alaska-Natives/wiki/Considerations-for-engaging-communities-with-respect)
- [ ] co-design training materials from [gdrive](https://drive.google.com/drive/folders/1c3crJ7oryvWNaSUCX0Yok6raZPsK06Rb) 
- [ ] slack [link](https://gsa-tts.slack.com/archives/C02DJFR0V/p1672339457262459_ to thread and video clip on co-design and power 
- [ ]  #co-design Slack channel to optionally engage folks who took the training
- [ ] introduction to [radical participatory design](https://www.cambridge.org/core/journals/design-science/article/an-introduction-to-radical-participatory-design-decolonising-participatory-design-processes/63F70ECC408844D3CD6C1A5AC7D35F4D) 

**Definition of done**

- [ ] One of the POs has approved the change
- [ ] Outreach approval (if needed)

**Comment by bpdesigns** [comment]
Closing this as it refers to practices we have not implemented and the design principles of the site are to reflect the current state of our practice
