### ISSUE TITLE
🟡 Create blog post based on communities content

### ISSUE THREAD

**Issue by amandarkennedy** [18F/guides#295]
**Background**

We are adding content to the UX guide on conducting research with communities and non-native English speakers, based on the following issues:

- 18F/guides#293 
- 18F/ux-guide#360 
- 18F/ux-guide#320 

We would like to turn this content into an 18F blog post that summarizes these best practices and spotlights these additions to the guide.

We will still need to create an issue in the blog repo for this content, but wanted to add an issue in this repo so we can track this idea during our team's sprint planning and standup.

**Acceptance criteria**

- [ ] Have you turned this into a formal blog post request in the blog repo?

**Tasks**

- [ ] discuss this idea during standup or sprint planning.
- [ ] Turn this idea into a formal blog post request in the blog repo.

**Comment by amandarkennedy** [comment]
@juliaklindpaintner great question. I think so! Would it be okay if I give it some thought while my other blog post is in review?
