### ISSUE TITLE
🟡 Part 2 - UX Guide - update language on working with partners

### ISSUE THREAD

**Issue by bpdesigns** [18F/guides#299]
**Content update needed** 
The "[Meet partners where they are](https://ux-guide.18f.gov/our-approach/meet-partners-where-they-are/)" section is primarily about maturity of the partner and collaboration tools. This is a follow up issue of #[325](https://github.com/18F/ux-guide/issues/325)

**Describe the change you'd like to see**
This page should also describe how to engage with the partner across the design process.

**Acceptance Criteria**
- [ ] The [Meet partners where they are](https://ux-guide.18f.gov/our-approach/meet-partners-where-they-are/) include content on engaging partners across the design process
- [ ] Related TTS Handbook pages are reviewed and a decision is made to consolidate or leave that handbook content as is. 

**Tasks**
- [ ] add to the [Meet partners where they are](https://ux-guide.18f.gov/our-approach/meet-partners-where-they-are/) how to engage with the partner across the design process
- [ ] Link to sections of the ux guide where partners could be involved, such as, in planning and observing research as well as during synthesis.  
- [ ] Consider if the two pages in the TTS handbook that talk about how partnership should be linked to or updated as part of the process. If so add these tasks to this issue or create a new issue to address that task.

**Additional context**
Related TTS Handbook pages:
- [Consulting with partners](https://handbook.tts.gsa.gov/18f/projects-partners/how-we-relate-to-partners/)
- [How we collaborate](https://handbook.tts.gsa.gov/general-information-and-resources/how-we-collaborate/#are-there-times-we-shouldn-t-collaborate-with-our-partners)

**Add reviewers** 
@bpdesigns 
@MelissaBraxton

**Comment by bpdesigns** [comment]
@lauranash18f can you share your draft content? I'm considering closing this issue without addressing it as we talk about collaborating and team roles across the core ux guide pages.
