### ISSUE TITLE
🟡 Outline product design goals for research practices Part 2

### ISSUE THREAD

**Issue by bpdesigns** [18F/guides#306]
### Description of the work
The 18F UX Guide documents our practices well around research. But, it has a [light design section](https://ux-guide.18f.gov/design/) that does not reflect our product design practices.
This ticket is to explore what this section could look like if we wanted to use this space to document 18F product design practices.

### Goals of this ticket 
- [x] Review Part 1 ticket in the DA Team board- [Define product design goals for UX guide Part 1](https://github.com/18F/delivery-assurance/issues/123) 
- [x] Identify product design practices on projects
- [x] Identify if and where guidance on these practices already exists at 18F
- [x] Create an initial outline for the design section (identifying a few sections of work is ok) and share with @cmajel, and @juliaklindpaintner and in slack with the product design team for review

### Acceptance Criteria
- As a future team member, I can easily find what information is needed so that I know where to target my investigation and make an informed decision about adding product design content to the UX guide.

### Point of contact on this issue
You can reach out to me, @cmajel, and @juliaklindpaintner for questions about product design practices.
@bpdesigns is the product owner of the UX Guide who will review and approve the final issue.

Billable?
- No
If yes, tock code:

### Skills needed
 - Any human
-  Design
-  Content
 
### Timeline
Does this need to happen in the next two weeks?
- No

### How much time do you anticipate this work taking?
2 weeks

**Comment by cantsin** [comment]
I think we need to break this down further, specifically between research and implementation. Suggested breakdown (from what I understand of this ticket):

1. What product design practices are we doing on projects and what are people referencing to understand that
2. What should we be publishing to document/store/disseminate that practice to ourselves and others 
3. Write the content for it (and publish it?)

@bpdesigns the main reason i think this should be broken down is because this is probably too big for a 2w increment.

**Comment by bpdesigns** [comment]
@cmajel please see the comment above for modifications needed to this ticket to refine it for the TLC team.

**Comment by cmajel** [comment]
Popping in quickly to signal that there's a [part one to this ticket](https://github.com/18F/guides/issues/486) that gets to bullet #1, and names some potential practices, including:

- Sharing design power with others, and how to bring people into the design process
- Prototyping across fidelity and why (sketching vs wireframing vs coded prototype)
- Comparative analysis
- Design documentation and annotation approaches (working with devs)
- Design principles

I'll refine more in a few days.

**Comment by quarterback** [comment]
we're going to have @beepdotgov & @nicoleslaw work on this set of tickets. cc: @bpdesigns @cmajel

**Comment by beepdotgov** [comment]
Hey all! @austinhernandez and @nicoleslaw and I have been thinking about what an expanded Design section could look like on the UX Guide, and we've come up with a _preliminary_ outline:

https://docs.google.com/document/d/1VhItf0crhgM78h5Bz9Td8RoNUObeWm52I15VZ_oAHGQ/edit

Our next steps are to bring this to the next Product Design huddle, solicit some feedback from the team, and identify what our next pass needs to incorporate.

**Comment by austinhernandez** [comment]
Here is the workshop for the Product Design huddle on Thursday 6/27—[Mural](https://app.mural.co/t/gsa6/m/gsa6/1719265179848/8d1fa4d5cf2c33c758898560902bdbe33da7ecaa?sender=austinhernandez5199)

Open to feedback, @beepdotgov and @nicoleslaw, or lmk if it doesn't make sense

**Comment by beepdotgov** [comment]
@austinhernandez Looks fantastic to me! Left a couple small comments, but no blockers; thanks so much for pulling this together!

Really looking forward to Thursday's discussion.

**Comment by beepdotgov** [comment]
Yesterday, we got some stellar feedback on our outline from the Product Design team. From here, @austinhernandez will be taking point on revising the outline (with support from @nicoleslaw) and running it past @cmajel for review/approval.

(Taking my face off the issue since I'm rolling off TLC, but the design guide is in good hands!)

**Comment by austinhernandez** [comment]
Based on feedback from the team and synthesis with @beepdotgov and @nicoleslaw I rearranged some stuff in the outline.

@nicoleslaw and @cmajel can I get a review on [this new outline in mural (section 4)](https://app.mural.co/t/gsa6/m/gsa6/1719265179848/8d1fa4d5cf2c33c758898560902bdbe33da7ecaa?sender=u4deb25d7c38e17a69e7d2021)? Christine, I believe you are the final approver on this

**Comment by nicoleslaw** [comment]
Awesome! I added some smaller comments in Mural.

**Comment by cmajel** [comment]
This is great, THANK YOU @austinhernandez @nicoleslaw and @beepdotgov for taking something vague to something much more concrete that we can work from  🎉 

I think we got what we came from here on this ticket and can close it out. 

@bpdesigns @quarterback let's keep talking about the best channel/method for promoting this work.
