### ISSUE TITLE
New Design research Ethics content in the UX Guide

### ISSUE THREAD

**Issue by bpdesigns** [18F/guides#308]
## Background
18F researchers have become more nuanced in how ethics informs their work but these practices and considerations are not documented clearly

## Acceptance criteria
 Readers of the Ethics page will understand how 18F team members Ethics inform their work

## Tasks 
- [ ]  Refine updates in word [doc]([doc](https://docs.google.com/document/d/1PTvZcXjOrbcJmwNo5UM71k78dr_NNi6nf9gcBUnyHBI/edit#)) and share out in slack for design and research team input
- [ ] Get input from design and research teams, either in huddles, crit or guild meetings.
- [ ]  Update the page in github

**Comment by juliaklindpaintner** [comment]
Changes were made to the Ethics page in the UX Guide last year, so closing this issue.
