### ISSUE TITLE
🟢 Clean up resource permalinks in UX Guide

### ISSUE THREAD

**Issue by AnitaYCheng** [18F/guides#309]
Observation while replatforming: Some `resource` pages have `/research/` permalinks, which makes orientation in side-navs confusing. It's unclear where the page can actually be found within the UX Guide.
```[tasklist]
### Tasks
- [ ] Review the links on the resources page
- [ ] Determine which of them should be under "resources" rather than "research"
- [ ] Make the changes
```

**Comment by bpdesigns** [comment]
It looks like the [Research alignment workshop](https://guides.18f.gov/ux-guide/research/alignment-workshop/) is the only link that has the wrong permalink.  

However there is an Information Architecture issue here. Some of the pages linked in [resources](https://guides.18f.gov/ux-guide/resources/) can only be discovered clicking on the link within that page. There should be another issue on adding menu navigation to these items

**Comment by bpdesigns** [comment]
Closing this ticket as IA will be addressed in future tickets
