### ISSUE TITLE
[EPIC] Review old UX Guide issues

### ISSUE THREAD

**Issue by christophermather** [18F/guides#350]
We have a number of old issues that have recently been pulled over from the old UX guide repo.

We need to review them and decide:
1. If they are still relevant and should be refined + prioritized
2. Or if they are no longer relevant and should be closed

Recommended steps:
- [ ] UX Guide code owner (@juliaklindpaintner) takes a pass on the issues
- [ ] UX code owner makes quick decisions
- [ ] Adds a 🟢, 🟡 or 🔴 to the issue in the Title field

🟢 means yes, this is still relevant
🔴 means no, this is no longer relevant
🟡 means needs more information/time to make a decision

**Comment by juliaklindpaintner** [comment]
Reviewed all open issues and added 🟡🟢🔴 ahead of the titles. I closed any that I labeled as 🔴.

**Comment by juliaklindpaintner** [comment]
@bpdesigns I wanted to draw your attention to this issue for UX Guide issues — this is where I probably should have caught that meta descriptions already existed, so I wonder if there is other stuff that you would characterize differently... Take a look at your leisure. I don't think there's any rush.

**Comment by bpdesigns** [comment]
Thanks @juliaklindpaintner I'll review these to see if they are still relevant.
