### ISSUE TITLE
Methods and UX guide both have an interview checklist, debrief, etc

### ISSUE THREAD

**Issue by echappen** [18F/guides#356]
### Tasks
- [x] Update any links currently pointing to the methods version of the interview checklist (locally as `/methods/interview-checklist/`, example [here](https://guides.18f.gov/methods/interview-checklist/) to point to the [UX guide's](https://guides.18f.gov/ux-guide/interview-checklist/)

- [x] Update any links currently pointing to the methods version of the interview debrief: [methods](https://guides.18f.gov/methods/interview-debrief/)

- [x] Update any links currently pointing to the methods version of the interview script: [methods](https://guides.18f.gov/methods/interview-script/) to point to the [ux guide](https://guides.18f.gov/ux-guide/interview-script/)

- [x] Update any links currently pointing to the methods version of the usability test script: [methods](https://guides.18f.gov/methods/usability-test-script/) to point to the [ux guide](https://guides.18f.gov/ux-guide/usability-test-script/)

### Acceptance Criteria

- [x] links pointing to the checklist, debrief, interview script, and usability script on the Methods site, now point to their respective UX guide equivalent pages

**Comment by echappen** [comment]
@juliaklindpaintner @christophermather Would you consider resolving this as in-scope for the [methods migration epic](https://github.com/18F/guides/issues/224), or would it be best to handle post-migration?

**Comment by MelissaBraxton** [comment]
My read on this is that we're replacing (rather than removing) the links to the somewhat redundant and outdated versions of these checklists on the methods site in favor of the more readable versions that are part of the UX guide, which I think this is a great idea!

**Comment by c-collins** [comment]
Discussed with @bpdesigns and @MelissaBraxton. This ticket just represents the updated links. A new ticket will be opened for the purpose of creating an automatic redirect from the Methods pages to the UX Guide pages, in case external links exist.
