### ISSUE TITLE
[EPIC] Review old Brand Guide issues 

### ISSUE THREAD

**Issue by christophermather** [18F/guides#377]
We have a number of old issues that have recently been pulled over to the new Guides repo from the old Brand guide repo.

We need to review them and decide:
1. If they are still relevant and should be refined + prioritized
2. Or if they are no longer relevant and should be closed

Recommended steps:
- [x] Brand Guide code owner takes a pass on the issues
- [x] Brand code owner makes quick decisions
- [x] Adds a 🟢, 🟡 or 🔴 to the issue in the Title field

🟢 means yes, this is still relevant
🔴 means no, this is no longer relevant
🟡 means needs more information/time to make a decision

Following these quick decisions, we should do a few follow-on steps, including: close out all 🔴s, pull all 🟢s and 🟡s into the TLC project backlog and tag all 🟡s with `needs refinement`.

```[tasklist]
### Tasks
- [ ] https://github.com/18F/guides/issues/317
- [ ] https://github.com/18F/guides/issues/318
- [ ] https://github.com/18F/guides/issues/319
```

**Comment by bpdesigns** [comment]
@igorkorenfeld following up to see if this is work you want to take on as the 18F Brand code owner.

**Comment by igorkorenfeld** [comment]
Thanks Ben, yes I'll review

**Comment by bpdesigns** [comment]
@igorkorenfeld moving this to icebox for now. Please close this ticket after your review. There are two tasks to review and if you want to close all three as things we should not work on or move the two open ones to candidates for prioritization either would be fine ways to resolve this. Thank you!

**Comment by igorkorenfeld** [comment]
Thanks @bpdesigns, I reviewed those and added the color circles a couple months ago back so I'll go in an close the remaining issues.

**Comment by bpdesigns** [comment]
Thanks Igor!
