### ISSUE TITLE
[EPIC] Review old De-risking Guide issues 

### ISSUE THREAD

**Issue by christophermather** [18F/guides#378]
We have a number of old issues that have recently been pulled over to the new Guides repo from the old De-risking guide repo.

We need to review them and decide:
1. If they are still relevant and should be refined + prioritized
2. Or if they are no longer relevant and should be closed

Recommended steps:
- [x] De-risking Guide code owner takes a pass on the issues
- [x] De-risking code owner makes quick decisions
- [x] Adds a 🟢, 🟡 or 🔴 to the issue in the Title field

🟢 means yes, this is still relevant
🔴 means no, this is no longer relevant
🟡 means needs more information/time to make a decision

Following these quick decisions, we should do a few follow-on steps, including: close out all 🔴s, pull all 🟢s and 🟡s into the TLC project backlog and tag all 🟡s with `needs refinement`.
```[tasklist]
### Tasks
- [ ] https://github.com/18F/guides/issues/312
- [ ] https://github.com/18F/guides/issues/313
- [ ] https://github.com/18F/guides/issues/314
- [ ] https://github.com/18F/guides/issues/315
```

**Comment by adunkman** [comment]
@christophermather all done with code owner review — I’ll send this back your way, but feel free to reassign over to Julia or James if this is a TLC lead task now!

**Comment by christophermather** [comment]
Thank you! Looks like I'm hanging around in TLC for another increment, so I'll coordinate w/ Julia and James.
