### ISSUE TITLE
As a site visitor, I'd like access to some documents/resources that are currently locked

### ISSUE THREAD

**Issue by christophermather** [18F/guides#379]
### A description of the work

In two separate issues (see below), we've received requests to open up some of our 18F resources that are currently locked and only for 18F/GSA use. 

We should evaluate these resources and decide if we'd like to open them up.

More broadly, we should also consider establishing a policy for what could/should be public versus what needs to stay private and locked.

### Reproduction steps (if necessary)

- [ ] Review issues associated w/ this issue
- [ ] Decide if documents mentioned should be shared
- [ ] Consider establishing a policy for public versus private documents (if it doesn't exist already)

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### Acceptance Criteria

- [ ] Decisions have been made on the two issues mentioned
- [ ] A public-versus-private policy has either been established or surfaced

**Comment by bpdesigns** [comment]
Closing as the linked issues are completed. 

@adunkman flagging the last item is a Guides policy question and is suggesting creating a policy for public versus private documents.
