### ISSUE TITLE
[EPIC] As a site visitor, I'd like an improved user experience on the Guides

### ISSUE THREAD

**Issue by christophermather** [18F/guides#389]
### A description of the work

As part of iterative improvement of the Guides, we should review some past issues pulled from old Guides repos for opportunities to improve the site's UX.

Some of these recommendations may be guide-specific; most should be considered for application to all guides.

See below task list for issues.

### Reproduction steps (if necessary)

- [ ] Review issues in task list
- [ ] Decide if issue is still valid/worth addressing
- [ ] Determine if applicable only to a specific guide, or applicable to all guides

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No
