### ISSUE TITLE
[EPIC] As the product owner of guides, I'd like to standardize processes and decision-making

### ISSUE THREAD

**Issue by christophermather** [18F/guides#391]
### A description of the work

Since we've consolidated Guides onto one platform and one repo, we have an opportunity to make our decision-making, governance and overall processes more standardized.

There are several issues from old repos that may help contribute to this goal. There are also some tasks that will require new discovery, planning and agreement. 

See the task list below for issues.

### Skills Needed

- [ ] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

```[tasklist]
### Tasks
- [ ] https://github.com/18F/guides/issues/292
- [ ] https://github.com/18F/guides/issues/407
- [ ] https://github.com/18F/guides/issues/297
- [ ] https://github.com/18F/guides/issues/148
- [ ] https://github.com/18F/guides/issues/399
- [ ] https://github.com/18F/guides/issues/401
- [ ] https://github.com/18F/guides/issues/405
```

**Comment by bpdesigns** [comment]
@adunkman for awareness that this Epic is out of scope for TLC as they relate to guidance and policy so I'll be closing it
