### ISSUE TITLE
Clarification of "time required" values

### ISSUE THREAD

**Issue by AaronUXD** [18F/guides#394]
## Overview
Update 18F Methods time required to be specific 

## Tasks
- [x] create a spreadsheet with how "time required" is described on each site 
- [x] make a recommendation for a standard way to describing time required across the methods 
- [x] review by a member of the TLC team 
- [x] update the spreadsheet with text that meets the standards

## Acceptance Criteria
- [x] spreadsheet with consistent way of describing the time required to complete each 18F method.
**Implementation ticket to follow**

## Background
Great site! Could you clarify what the "Time Required" represents, or where it came from? (e.g. is this what 18f uses for sprint planning estimates?)

Saying time required "it depends" isn't necessarily helpful either, but noticed some variation in how it's used -

Some examples:

### Represents time from end-users, but not preparation or analysis from team:

![image](https://user-images.githubusercontent.com/9051299/27309009-a1ded7c2-551f-11e7-9db3-b82b113e756e.png)

### Seems oddly low (e.g. design pattern library: 1-2 hours per pattern, does this suggest that the US design standards were created and posted by one person in 1-2 weeks?)
![image](https://user-images.githubusercontent.com/9051299/27308115-08406bde-551b-11e7-8b48-91e77adb78f2.png)

### This one seems to make more sense in how its phrased - broader range of hours for creation activity, and also time per person to give feedback, could add a few hours to gather and publish results to team. (The total time still seems low for someone to estimate sprint task time though.)
![image](https://user-images.githubusercontent.com/9051299/27309284-16952084-5521-11e7-8e4e-8c1d139c8246.png)

**Comment by qmanderson1** [comment]
Recommendation could be informed by other team members in slack.

**Comment by qmanderson1** [comment]
[Time Require Spreadsheet/Recommendations here](https://docs.google.com/spreadsheets/d/1hfSkIcgl7_O3EqHFl2G14R_dib-WPLzq8440ONEWGCY/edit#gid=0)

**Comment by boonerang** [comment]
This looks great, nice to see these all in one place.

It’s almost impossible to get specific on many of these activities so the “Average X-Y” allow for flexibility of the skill level of the individual or team doing the work.

I’ve adjusted most of the suggested to include average ranges and allowances for varying levels of skill in the spreadsheet.

**Comment by bpdesigns** [comment]
@qmanderson1 please review @boonerang's updates. Let me know once you've done. I'll give it a final review. Thanks

**Comment by qmanderson1** [comment]
@bpdesigns I've reviewed Boon's updates. This ready for your review. Thank you.

**Comment by bpdesigns** [comment]
Thanks @qmanderson1 ! This is ready to close.

**Comment by michelle-rago** [comment]
Looks like we have proposed updated for the "time required" values. We now need to decide if we're going to keep this information as part of the cards.
