### ISSUE TITLE
EPIC - duplicate content between Methods and the 18F UX guide (and add redirects)

### ISSUE THREAD

**Issue by andrewmaier** [18F/guides#397]
POs to break out the specific places that have duplicative content across sites.

### Migrate
- [ ] Example interview script
- [ ] Example usability test script
- [ ] Interview checklist
- [ ] Post-interview debrief
- [ ] Running issue log

### Remove duplicate fundamentals
- [ ] Recruiting
- [ ] Incentives
- [ ] Privacy

### Update
- [ ] Setup redirects
- [ ] Any links in the current resources
- [ ]  Privacy act statement for design research
