### ISSUE TITLE
EPIC: Link templates or examples of design artifacts from the Methods

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/guides#400]
### Goal
Make 18F design templates publicly available for 18F Methods cards 

### Break-out issues
- [#610](https://github.com/18F/guides/issues/610)
- [#611](https://github.com/18F/guides/issues/611)
- [#613](https://github.com/18F/guides/issues/613)
- [#614](https://github.com/18F/guides/issues/614)
- [#615](https://github.com/18F/guides/issues/615)
- [#616](https://github.com/18F/guides/issues/616)
- [#619](https://github.com/18F/guides/issues/619)
- [#620](https://github.com/18F/guides/issues/620)
- [#621](https://github.com/18F/guides/issues/621)

### Tasks 
- [x] review [airtable of templates](https://airtable.com/apptZqDMNhC3sEtXZ/tbl7PysIe9LJ93SiQ/viwNF7XLhUiiqP05l?blocks=hide) 
- [x] create a list of ones to make public
- [x] review with @bpdesigns who will review with the Design supervisory team
- [ ] determine what format the template should be in (doc, pdf, etc)
- [ ] do an accessibility review of template
- [ ] do a review for PII and other non-public information
- [x] determine which method card each template should be associated with

### Acceptance Criteria 
- [ ]  determine which method card each template should be associated with

### Background

📝 [Notes doc](https://docs.google.com/document/d/1V_A4coumYRphzgFt50YST6DFrqlRy9fmPdefpXxYOQk/edit)

A Mural voting activity on 12/10/18 in the 18F Design Huddle collected most commonly produced artifacts by 18F designers. Some aligned with existing methods (e.g., Journey mapping, personas, interview guides). 

We should consider linking to examples of these artifacts from existing methods as a way to further illustrate the approach and/or link existing/create new templates for these artifacts (e.g., for personas).

Definition of done: Creation of new issues to collect examples or create/link templates OR explanation of why this suggestion was rejected.

**Comment by nicoleslaw** [comment]
This was mistakenly prioritized so I am unassigning myself in favor of higher pri tickets. However, I would recommend reviewing this [Mural](https://app.mural.co/t/gsa6/m/gsa6/1542810701542/f8e88448d2501699b6ffaa1f8866c83ebb449006?sender=julialindpaintner1638) from Julia.

Some top contenders for examples or templates are: interviews, style tiles, journey mapping, service blueprints, prototypes, and wireframes.

**Comment by bpdesigns** [comment]
[list of design templates](https://airtable.com/apptZqDMNhC3sEtXZ/tbl7PysIe9LJ93SiQ/viwNF7XLhUiiqP05l?blocks=hide)

**Comment by bpdesigns** [comment]
@nicoleslaw FYSA I've updated this ticket based on a conversation of the design supervisory team. We have templates but have not found time to make them public yet

**Comment by bpdesigns** [comment]
Could be a good pairing ticket with someone newer and someone who has been at 18F for a while

**Comment by bpdesigns** [comment]
Once this work is complete, create an implementation ticket

**Comment by melchoyce** [comment]
Notes/tracking doc started here: https://docs.google.com/document/d/1V_A4coumYRphzgFt50YST6DFrqlRy9fmPdefpXxYOQk/edit?usp=sharing

**Comment by melchoyce** [comment]
Went through and reviewed all of the resources. They roughly fall into a couple categories:

- The resource literally just links to the Method card
- Is a good resource and can be added to a Method card
- Is a good resource, but doesn't have a Method card it fits under yet
- Isn't something we want to share externally

[You can see my breakdown, along with notes, in the doc](https://docs.google.com/document/d/1V_A4coumYRphzgFt50YST6DFrqlRy9fmPdefpXxYOQk/edit).

**Comment by bpdesigns** [comment]
@melchoyce this is great. Thank you! I'm working through this. Likely will be early next week before I'm done with my review

**Comment by bpdesigns** [comment]
@melchoyce as a decision point for some of these on the fence use cases and where (1) the directions to work through the method are clear and (2) its not easy to find a standard visual in our Gdrive or murals, lets not create a template.

**Comment by bpdesigns** [comment]
Actually @melchoyce done with initial review. Happy to meet about this early next week if you want to chat about any of it.

**Comment by melchoyce** [comment]
All of your notes make sense to me! Let's touch base next week to chat about the next couple steps. In the meantime, I'll start noting down what format each template is currently in, and make notes on what format might be best for release.

**Comment by melchoyce** [comment]
Formats: https://docs.google.com/document/d/1V_A4coumYRphzgFt50YST6DFrqlRy9fmPdefpXxYOQk/edit#heading=h.l8n5fhbysoq0

**Comment by bpdesigns** [comment]
@melchoyce I've reviewed and found a time for us to chat tomorrow. Please move the time if needed. TY!

**Comment by melchoyce** [comment]
Started drafting next steps: https://docs.google.com/document/d/1V_A4coumYRphzgFt50YST6DFrqlRy9fmPdefpXxYOQk/edit#heading=h.lnqqbcaogvaq

**Comment by bpdesigns** [comment]
Thanks @melchoyce !

**Comment by bpdesigns** [comment]
reviewing templates individually
