### ISSUE TITLE
Make UX Guide "resource" titles consistent and easy to recognize in search results 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/guides#402]
**background**
This issue is following up on a recommendation from analytics research done last year and summarized in [this deck.](https://docs.google.com/presentation/d/1trsB6MLyrIEL4cbvsqMVtNujFCTQTE7OYhcj14FDag4/edit#slide=id.g78bab2de6b_0_24)

**acceptance criteria**
- [ ] "resources" use consistent naming conventions
- [ ] considerations re: naming existing and new resources are documented in GitHHub

**tasks**
- [ ]

**Comment by bpdesigns** [comment]
@claireb-gsa do you have thoughts on expanding or changing this ticket considering IA discussions we're having?

**Comment by claireb-gsa** [comment]
Yeah - I think this fits in nicely with the more general restructuring we're talking about. @bpdesigns 

There are sort of two issues here:
- naming of the resources (these are all over the place)
- naming of the page content

Since we're talking about organizing/moving/fixing the resources, I think the page names could be dealt with as a part of that update - restructuring the resource page, doing consistent titles, and then making sure they're all living under /resources.  

The page content titles (Stay lean, plan, do) may end up changing as we split apart that content into smaller pieces - so renaming them in their current structure probably isn't worth it.  

I think we can keep this ticket for traceability, but maybe update it to be specific to the resources renaming, and link it to the other shifts that need to happen to clean that area up?

**Comment by bpdesigns** [comment]
@claireb-gsa feel free to update the ticket as it makes sense. TY!

**Comment by claireb-gsa** [comment]
Updated ticket! 

For posterity, removed task 
- [ ] draft new titles for the Stay lean, Do, Plan pages that make it easy to understand what content exists on these pages

That title work should happen as a part of the reorg of content more generally.

**Comment by alia-salim** [comment]
Moving this to "in review" based on conversation about statuses in retro yesterday. I'm looking for some feedback from @claireb-gsa ([see comments on this doc](https://docs.google.com/document/d/1kFliU-aydW0ejvN0rn4LDRJjZGFM8yjQulx2W3WQGSE/edit)); when that's resolved I'll tag Ben in again.

**Comment by claireb-gsa** [comment]
@alia-salim I replied to the comment in the doc - and left other random thoughts. Decision is in your court, and then I think we're good to proceed

**Comment by alia-salim** [comment]
@claireb-gsa thank you! @bpdesigns, based on Claire's feedback, I changed the label in my suggested title format from  "example" to "resource" and submitted a pull request to change the titles of the 12 affected guide pages. 

(It's my first try at using GitHub Desktop, so please let me if there are things I've done incorrectly/not the way you prefer, even if it's minor details!)

**Comment by bpdesigns** [comment]
@alia-salim this should be good to go! Thank you. Please move this to done.

**Comment by alia-salim** [comment]
I've marked this "done" with some acceptance criteria open.

> all UX guide resources are in the correct place in the site architecture (/resources) with a visible left navigation and old links redirect

This work is now reflected in [#583 ](https://github.com/18F/guides/issues/583)

> pattern for naming resources is defined and documented in the Guides GitHub`

There is currently no Wiki for the new, centralized guides repo. Per Claire, one may be created in the future, but for now, documenting the naming convention in this ticket is OK. **Resources in the UX guide should be named/labeled like this:**

`Resource: [Name of resource]`

e.g. "Resource: Stakeholder interview script"

**Comment by bpdesigns** [comment]
TY!

**Comment by nateborr** [comment]
The PR to update the resource page titles was approved in June but not actually merged. I have done so now: https://github.com/18F/guides/pull/624
