### ISSUE TITLE
Research how to optimize UX Guide IA and navigation 

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/guides#403]
**background**
This issue is following up on a recommendation from analytics research done last year and summarized in [this deck.](https://docs.google.com/presentation/d/1trsB6MLyrIEL4cbvsqMVtNujFCTQTE7OYhcj14FDag4/edit#slide=id.g78bab2de6b_0_24) Resources are among the most searched for items, but the "resources"  header is not currently part of the site's top level navigation--it's somewhat buried under "about this guide." 

There are likely additional improvements we can make to navigation, but we'll want to conduct some user research to inform a more holistic approach to refining the site's information architecture to address this and other usability issues.     

We might consider splitting research planning, conducting research, and analysis into separate tasks to enable each one to be done in a week. 

**acceptance criteria (we'll know we're done when...)**
- [ ] We have a prioritized list of refinements to make to the navigation 
- [ ] These recommendations address considerations for making "resources" findable from the site's main navigation

**tasks**
- [ ] Write user research plan (goals, hypotheses, methods)
- [ ] Write research facilitation script (if moderated testing)
- [ ] Recruit users (if needed)
- [ ] Conduct research sessions 
- [ ] Analyze & synthesize research
- [ ] Write up recommendations

**Comment by bpdesigns** [comment]
Closing as this will be addressed in new tickets to come on IA
