### ISSUE TITLE
Document a process for checking whether these sites meet GSA IT site requirements checklist and identify follow up actions needed

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/guides#405]
**Point of contact**
@MelissaBraxton 

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

**How much time do you anticipate this work taking?**
About 2 weeks

**Background**
The Methods site hasn't had a major refresh since GSA IT updated their site requirements. It's timely for us to review the site and ensure that it meets requirements. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] We've identified any possible compliance  issues with the 18F Methods site
- [ ] Follow on actions to address compliance findings are documented as new issues.

**Tasks**
- [ ] Review site against GSA IT checklists[ here](https://digital.gov/resources/checklist-of-requirements-for-federal-digital-services/?dg), and [here](https://docs.google.com/spreadsheets/d/1m0znObFFlJ7kRVpODr97T-LGkz0YWdJiDp9LbY24ahE/edit#gid=1561864569)
- [ ] Create new issues for any work on the 18F Methods site that may be needed to ensure compliance.

- [ ] Decide on a centralized place to document a process for ensuring our sites' compliance 
- [ ] Review [this documentation](https://docs.google.com/document/d/1SBBpMN2bsy5Hu44XWvd7WY-vnhq5WFK7kAkEYEj94t8/edit#heading=h.2z3msg6yx9nt) as a starting point for how we formalize this process
- [ ] Document the process 

- [ ] Write a new issue with considerations for how we might automating how we can check re: whether a site meets requirements
