### ISSUE TITLE
Document 18F Methods site architecture in the wiki

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/guides#407]
**Point of contact**
@MelissaBraxton 

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

**How much time do you anticipate this work taking?**
3-4 days including feedback/review

**Background**
We want to document the site architecture in the wiki to help folks working on the site get oriented and up-to-speed quickly. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] The site architecture is live on the wiki
- [ ]  An engineer unfamiliar with the project can understand the site architecture after viewing the wiki content

**Tasks**
- [ ] Draft architecture diagram
- [ ]  PO review 
- [ ] Post architecture documentation to the wiki[ here](https://github.com/18F/methods/wiki/Site-architecture)
- [ ]  Accessibility review
