### ISSUE TITLE
NEW METHOD: Qualitative data analysis | coding

### ISSUE THREAD

**Issue by bpdesigns** [18F/guides#408]
### Point of contact on this issue
@bpdesigns or @MelissaBraxton 

______________________________________

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

**How much time do you anticipate this work taking?**
1-2 weeks

**Background**
We'd like to expand our methods to include an analysis method on coding qualitative research data.

If needed, this issue could be broken into 2: (1) draft content; (2) publish content

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ]  A method card for Qualitative research data coding is live on the site

**Tasks**
- [x] Review [Methods content vision](https://github.com/18F/methods/wiki) and [UX Guide content vision](https://github.com/18F/ux-guide/wiki)
- [x] Draft content in accordance with [this checklist](https://github.com/18F/methods/wiki/Content-editing-checklist#standard-method-pages)
- [ ] ~Link to the 18F UX guide in this [area](https://ux-guide.18f.gov/research/make-research-actionable/#from-data-to-insights).~ 
- [ ] Writing lab review - post in #helpwanted, and @writing-editors and ask for someone to review. 
- [ ]  PO review (@quarterback)
- [ ]  Accessibility review

**Comment by boonerang** [comment]
Edits made, should be good to go now.

**Comment by bpdesigns** [comment]
@boonerang looks good! Feel free to close this ticket.

**Comment by bpdesigns** [comment]
@a-chappelear @boonerang reopening this ticket based on comments. Feel free to reassign yourselves to this ticket. Thanks

**Comment by a-chappelear** [comment]
chatted w/ Melissa about this a bit this morning (where to put in IA) - will assign myself (if not by tomorrow, can have it in next increment + return to the implementation ticket) @bpdesigns @boonerang

**Comment by a-chappelear** [comment]
@MelissaBraxton @bpdesigns & @boonerang - I made a few edits to the method card and also renamed it to "Coding qualitative data". Let me know if this helps clarify / is more actionable: [new copy, didn't want to overwrite the prev](https://docs.google.com/document/d/1yqxZCDmAvGM-T8oOUBCepH0HZVEpYdkV9pzR2pSyu5s/edit?usp=sharing)

**Comment by bpdesigns** [comment]
@MelissaBraxton @quarterback I recommend we take steps 2-4 of this [draft](https://docs.google.com/document/d/1yqxZCDmAvGM-T8oOUBCepH0HZVEpYdkV9pzR2pSyu5s/edit?usp=sharing) and further flush out the affinity mapping card. These cards overlap and the current affinity mapping is light on details.

**Comment by a-chappelear** [comment]
@MelissaBraxton, edited slightly based on your feedback! @bpdesigns - is your comment to remove the steps 2-4 or to edit the affinity card?

**Comment by bpdesigns** [comment]
@bpdesigns to review

**Comment by bpdesigns** [comment]
@a-chappelear my comment was an idea to combine this card with the Affinity Mapping card BUT I will defer to @MelissaBraxton and remove myself as one too many cook in the kitchen on this :)

**Comment by MelissaBraxton** [comment]
Let's keep both cards. Affinity mapping and qualitative coding are different methods with different use cases that both have a place in our canon. (i.e., affinity mapping is good for workshops and helping stakeholder engage with the data; qualitative coding is good for helping research teams conduct rigorous research)

**Comment by bpdesigns** [comment]
@a-chappelear @MelissaBraxton is the reviewer and approver of this ticket. TY!
