### ISSUE TITLE
NEW METHOD:  Expert walkthrough

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/guides#409]
**Background**
This issue covers the publication of a new method, **expert walkthrough.**   The scope is writing the content and implementing it, but we may need to break up content creation/implementation, depending on the availability of folks who could take this on. Walking through prototypes with a group of expert users to pull out issue. This is good for information dense services where complexity can't be reduced. 

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] A method card that covers expert walkthrough is live

**Tasks**
- [ ] Draft content in accordance with [this checklist](https://github.com/18F/methods/wiki/Content-editing-checklist#standard-method-pages)
- [ ] Open a new PR to implement the content
- [ ] PO review / revisions
- [ ] Accessibility review 
- [ ] Merge
