### ISSUE TITLE
NEW METHOD: Onsite intercept interview or "hallway" testing

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/guides#410]
**Point of contact**
@MelissaBraxton 

**Background**
This issue covers the publication of a new method, **intercept interview.**   The scope is writing the content and implementing it, but we may need to break up content creation/implementation, depending on the availability of folks who could take this on. The intent is for this method to cover recruiting users in a specific community to participate in research in situ and is explicitly _not online intercept recruiting_. This method should align with emerging UX Guide content on research with communities.  ([#360](https://github.com/18F/ux-guide/issues/360)).

Questions to consider: Is this 2 methods? intercept survey (discovery phase) hallway testing (validate phase)?  

Also consider reaching out to usa.gov for example re: how they've used this. 

Some references for inspo (these don't meet requirements to include as refs on the site though): 
[Nielsen Norman](https://www.nngroup.com/articles/recruiting-screening-research-candidates/)
[bcgov design research guide](https://bcgov.github.io/design-research-guide/activities/intercept.html#:~:text=Intercept%20testing%20is%20a%20form,usually%20lasts%20around%2015%20minutes.)
[Smashing mag](https://www.smashingmagazine.com/2016/02/the-art-of-the-intercept/)

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ] A method card that covers onsite intercept interview is live

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

How much time do you anticipate this work taking?
2 weeks

**Tasks**
- [ ] Review [Methods content vision](https://github.com/18F/methods/wiki) and [UX Guide content vision](https://github.com/18F/ux-guide/wiki)
- [ ] Draft content in accordance with [this checklist](https://github.com/18F/methods/wiki/Content-editing-checklist#standard-method-pages) and using [this template](https://docs.google.com/document/d/1gBNvcB-Wtn0xqiM1-yEhhfcdE6ghcI6UXjWSGg7l3Do/edit)
- [ ] Open a new PR to implement the content
- [ ] PO review / revisions
- [ ] Accessibility review 
- [ ] Merge
