### ISSUE TITLE
Create a template for examples of table-like diagramming methods

### ISSUE THREAD

**Issue by MelissaBraxton** [18F/guides#413]
**Point of contact**
@MelissaBraxton 

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [X] No

**How much time do you anticipate this work taking?**
A week

**Background**
We recently created an example service blueprint example for the service blueprint method! There are other modeling/diagramming methods that would really benefit from a visual example, and right now the methods are really only text. Two of them (mental model and journey map) may be able to leverage the service design styling as a template. 

This issue covers exploring whether the service blueprint example can be a template for creating visual examples of mental model and journey map. If we think this is a good direction, then we can create the template. 

Follow on issues could include using this template to create visual examples of (1) mental model and (2) journey map

**Acceptance criteria _(we'll know we're done when…)_** 
- [x] We've decided whether the service blueprint example would make a good template for visual examples of other table-like diagramming methods
- [ ]  If yes, we've made the template!

**Tasks**
- [ ] Consider potential example mental models and journey maps for inclusion in the methods and assess whether the service blueprint example would work as a template
- [ ] If yes, create the template 
- [ ] Create a PR to add the template to the mathod / layouts folder
- [ ] Accessibility review
- [ ] Add @MelissaBraxton as a reviewer

**Comment by bpdesigns** [comment]
Awaiting more info

**Comment by bpdesigns** [comment]
@MelissaBraxton and @amandacostello this is something that I did not have time to review

I think the state of this ticket is to approve the list of modeling/diagramming methods that would really benefit from a visual example. @MelissaBraxton in your earlier comment in this ticket you mentioned:

- Mental models
- Journey maps
- Storyboards

If that is the right list @amandacostello this is good to unblock and prioritize
