### ISSUE TITLE
NEW METHOD: System map

### ISSUE THREAD

**Issue by elisaachen** [18F/guides#414]
**Point of contact**
@elisaachen 

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

**Background**
This issue covers the publication of a new method, **system map.** The scope is writing the content and implementing it, but we may need to break up content creation/implementation, depending on the availability of folks who could take this on. The intent is to cover visualizing a system and leverage points within it, their relationship to each other, and feedback loops, etc. An internal system map you can reference from an 18F project is [here] but acknowledge that if we want to reference it we'd need to make it accessible (https://app.mural.co/t/gsa6/m/gsa6/1570719886942/deee38a791ae4921f60cd41ec2f16122537b0a89?sender=elisachen8995).

**Acceptance criteria _(we'll know we're done when…)_** 
- [ ]  A method card that covers system maps is live

**Tasks**
- [ ] Draft content in accordance with [this checklist](https://github.com/18F/methods/wiki/Content-editing-checklist#standard-method-pages)
- [ ] Open a new PR to implement the content
- [ ]  PO review / revisions
- [ ]  Accessibility review
- [ ]  Merge

**Comment by allisonpress** [comment]
Here is [a draft of this method card](https://docs.google.com/document/d/1NhwLYLd6LD4EuoEfYSUfj438b2zZXORUemF2oEubpy0/edit)

**Comment by allisonpress** [comment]
Could use support making [an example system map](https://app.mural.co/t/gsa6/m/gsa6/1570719886942/deee38a791ae4921f60cd41ec2f16122537b0a89?sender=ufc973137ec79924880690649) accessible

**Comment by bpdesigns** [comment]
@allisonpress to review with @elisaachen before moving forward with an accessibility review

**Comment by allisonpress** [comment]
@bpdesigns approved this pull request for this card this week! 🥳
