### ISSUE TITLE
[EPIC] Review old Methods issues

### ISSUE THREAD

**Issue by christophermather** [18F/guides#416]
We have a number of old issues that have recently been pulled over to the new Guides repo from the old De-risking guide repo.

We need to review them and decide:
1. If they are still relevant and should be refined + prioritized
2. Or if they are no longer relevant and should be closed

Recommended steps:
- [ ] De-risking Guide code owner takes a pass on the issues
- [ ] De-risking code owner makes quick decisions
- [ ] Adds a 🟢, 🟡 or 🔴 to the issue in the Title field

🟢 means yes, this is still relevant
🔴 means no, this is no longer relevant
🟡 means needs more information/time to make a decision

Following these quick decisions, we should do a few follow-on steps, including: close out all 🔴s, pull all 🟢s and 🟡s into the TLC project backlog and tag all 🟡s with `needs refinement`.

```[tasklist]
### Tasks
- [ ] https://github.com/18F/guides/issues/394
- [ ] https://github.com/18F/guides/issues/395
- [ ] https://github.com/18F/guides/issues/396
- [ ] https://github.com/18F/guides/issues/397
- [ ] https://github.com/18F/guides/issues/398
- [ ] https://github.com/18F/guides/issues/399
- [ ] https://github.com/18F/guides/issues/400
- [ ] https://github.com/18F/guides/issues/401
- [ ] https://github.com/18F/guides/issues/402
- [ ] https://github.com/18F/guides/issues/403
- [ ] https://github.com/18F/guides/issues/405
- [ ] https://github.com/18F/guides/issues/406
- [ ] https://github.com/18F/guides/issues/407
- [ ] https://github.com/18F/guides/issues/408
- [ ] https://github.com/18F/guides/issues/409
- [ ] https://github.com/18F/guides/issues/410
- [ ] https://github.com/18F/guides/issues/411
- [ ] https://github.com/18F/guides/issues/412
- [ ] https://github.com/18F/guides/issues/413
- [ ] https://github.com/18F/guides/issues/414
- [ ] https://github.com/18F/guides/issues/415
```

**Comment by bpdesigns** [comment]
Closing this Epic as reviewed. Items linked will be addressed as appropriate.
