### ISSUE TITLE
[EPIC] Review old Product Guide issues

### ISSUE THREAD

**Issue by christophermather** [18F/guides#418]
We have a number of old issues that have recently been pulled over to the new Guides repo from the old Product guide repo.

We need to review them and decide:
1. If they are still relevant and should be refined + prioritized
2. Or if they are no longer relevant and should be closed

Recommended steps:
- [ ] Product Guide code owner takes a pass on the issues
- [ ] Product code owner makes quick decisions
- [ ] Adds a 🟢, 🟡 or 🔴 to the issue in the Title field

🟢 means yes, this is still relevant
🔴 means no, this is no longer relevant
🟡 means needs more information/time to make a decision

Following these quick decisions, we should do a few follow-on steps, including: close out all 🔴s, pull all 🟢s and 🟡s into the TLC project backlog and tag all 🟡s with `needs refinement`.

**Comment by allisonnorman** [comment]
@christophermather Thanks for organizing such an easy-to-fulfill request! I made comments on the issues for either posterity, or for your review if needed.
