### ISSUE TITLE
Define product design goals for design research Part 1

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/guides#486]
Note: This was brought over from the TLC crew repo. 

### A description of the work
The 18F UX Guide documents our practices well around research. But, it has a [light design section](https://ux-guide.18f.gov/design/) that does not reflect our product design practices.

This ticket is to explore what this section could look like if we wanted to use this space to document 18F product design practices.

### Tasks
- [ ] Review the existing [Design section of the UX guide](https://ux-guide.18f.gov/design/), and understand where it came from
- [ ] Review [past conversations](https://docs.google.com/document/d/14yF0pbJn47RYxIVZxFRY-IcoxXXzdn_X1wjoKkaIxDA/edit) about a product design guide
- [ ] Identify questions that would need to be answered before adding to the design section

### Next phase of work - Part 2 
- [Outline product design goals for UX guide Part 2 [#398](https://github.com/18F/guides/issues/306)

Possible topics include:

- Sharing design power with others
- Prototyping across fidelity and why (sketching vs wireframing vs coded prototype)
- Comparative analysis 
- Design documentation and annotation approaches
- Design principles

#### Resources
[Product design guide notes from 2021](https://docs.google.com/document/d/14yF0pbJn47RYxIVZxFRY-IcoxXXzdn_X1wjoKkaIxDA/edit)

### Point of contact on this issue
You can reach out to me, @cmajel, and @juliaklindpaintner for questions about product design practices. 

**Billable?**
- [ ] Yes
- [x] No

**Skills needed**

- [ ] Any human
- [x] Design
- [x] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

**Timeline**
Does this need to happen in the next two weeks?

- [ ] Yes
- [x] No

How much time do you anticipate this work taking?
2 weeks or less 

### Acceptance Criteria

- [ ] As a future team member, I can easily find what information is needed so that I know where to target my investigation and make an informed decision about adding product design content to the UX guide.

**Comment by bpdesigns** [comment]
@cmajel is this completed? I see that Part 2 is in review

**Comment by bpdesigns** [comment]
closing as complete. NVM @cmajel I see this was a duplicate from a different repo :)
