### ISSUE TITLE
[Request] Add federal blueprint examples to link to from the Service blueprint method card

### ISSUE THREAD

**Issue by amandarkennedy** [18F/guides#488]
### A description of the work

**Note:** This ticket is transferring over from the internal service design sub-chapter trello board. 

Currently, the "[Examples from 18F](https://methods.18f.gov/decide/service-blueprint/#example-from-18f)" section of the method card has a hypothetical example. It would be helpful to include publicly available examples for federal government services.

This ticket involves collecting publicly available federal service blueprints, getting them reviewed, and linking to them in the method card.

### Point of contact on this issue

- Service design supervisors: @elisaachen @MelissaBraxton @lauranash18f 
- If you have any questions about how the ticket is written, the author is @amandarkennedy 

### Skills Needed

- [X] Any Human
- [X] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

2-3 days

### Acceptance Criteria

- [ ] Find at least 2 examples of federal service blueprints that are available to the public.
- [ ] Get them reviewed by one of the service design supervisors: @elisaachen @MelissaBraxton @lauranash18f 
- [ ] Add them to the method card under "Examples from 18F".
- [ ] Publish.

**Comment by amandarkennedy** [comment]
- Have been searching for publicly available examples but have only found [this one from USDA](https://coe.gsa.gov/docs/2019-09-Web-Lydia-Journey.pdf) so far.
- Put a call out on Slack [here](https://gsa-tts.slack.com/archives/C02AUUQ8R/p1709734752006149) and [here](https://gsa-tts.slack.com/archives/C0XUF8XL1/p1709734785036919).
- I will also consider posting in the UX COP listserv.
- Otherwise, may need to pause this ticket and pick up one of the other methods cards instead.
cc @juliaklindpaintner

**Comment by juliaklindpaintner** [comment]
Thanks for the update @amandarkennedy! That USDA one looks pretty nice at first glance. Is there any more context on the site that links to that pdf? I wonder if it would be helpful to link to a site rather than directly to the PDF from the Method card? 

I would encourage you to add whatever you find to the card (even if it's just the USDA one) — incremental improvement!

**Comment by amandarkennedy** [comment]
@juliaklindpaintner good call, here is the COE link for [better context](https://coe.gsa.gov/2019/12/18/cx-update-17.html). That makes more sense.

And to clarify — I meant that while I wait and see if others have ideas to include over the next day or two, I may pick up another ticket. Will still include the COE/USDA link and be able to complete this ticket this increment.

**Comment by juliaklindpaintner** [comment]
Ah, yes! Perfect!

**Comment by amandarkennedy** [comment]
Created a pull request [here](https://github.com/18F/guides/pull/498) and tagged @elisaachen for review
