### ISSUE TITLE
[Request]: Add new "user story" method card

### ISSUE THREAD

**Issue by amandarkennedy** [18F/guides#489]
### A description of the work

**Note:** This issue transferred over from the service design sub-chapter Trello board.

User stories are a critical element of how we work at 18F, and how we encourage our partners to work, too. We could create a new method card on the user story to help people understand what user stories are and how they can incorporate them into their way of working. 

### Skills Needed

- [X] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

2-3 days

### Acceptance Criteria

- [ ] Draft a method card for a user story.
- [ ] Determine which Methods section it should live under. 
- [ ] Get the content and IA reviewed. This could be either reviewed by one of the service design supervisors, @elisaachen @MelissaBraxton @lauranash18f, or someone from product.
- [ ] Publish the new method card.

**Comment by bpdesigns** [comment]
There is a quick footnote in the [derisking guide on user stories](https://guides.18f.gov/derisking/federal-field-guide/basic-principles/#fn1) that would be a good reference

**Comment by MelissaBraxton** [comment]
I think adding a method card for user stories makes a lot of sense! I could see it going in either the decide or make category.

**Comment by bpdesigns** [comment]
Thanks @sam-couch-18f bringing this to 18F Design team for feedback and review.
