### ISSUE TITLE
EPIC: Address bad links on guides.18f.gov

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/guides#531]
### What happened?

A scan of current links on the Guides sites conducted via https://github.com/18F/TLC-crew/issues/354 resulted in a [spreadsheet of bad links](https://docs.google.com/spreadsheets/d/1KibtrzcBX-Qig1S2uawd3SHak9yfeG6toHpFU7VKKNs/edit#gid=0) we want to clean up. This epic will track progress towards this goal. 

### Version

1.0.2 (Default)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
```[tasklist]
### Tasks
- [ ] https://github.com/18F/guides/issues/532
- [ ] https://github.com/18F/guides/issues/535
- [ ] https://github.com/18F/guides/issues/537
- [ ] https://github.com/18F/guides/issues/538
- [ ] https://github.com/18F/guides/issues/539
```

**Comment by bpdesigns** [comment]
All tasks completed
