### ISSUE TITLE
Fix links resulting in a 403 error on guides.18f.gov

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/guides#537]
### A description of the work

A sub-ticket of https://github.com/18F/guides/issues/531, this issue is to address the 403 errors identified by a scan of the guides.18f.gov website in March 2024. 

Anticipated tasks:
- [x] Filter [this spreadsheet](https://docs.google.com/spreadsheets/d/1KibtrzcBX-Qig1S2uawd3SHak9yfeG6toHpFU7VKKNs/edit#gid=0) in column H "Error code" by 403
- [x] Identify the bad link and look for a replacement
- [x] If possible, replace. If not easily identified, recommend either removing or replacing with something similar.
- [x] As you address the links, add your resolution in column A — either link to the PR for the fix or note why couldn't fix it.

### Point of contact on this issue

TLC co-leads

### Skills Needed

- [X] Any Human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### Acceptance Criteria

Flagged 403s have been addressed and either replaced or removed.

**Comment by bpdesigns** [comment]
waiting for a review from the engineering guide code owner

**Comment by cantsin** [comment]
@jasnakai can you help me out here, what can i do to unblock this? i see the relevant PRs seem merged already?

**Comment by jasnakai** [comment]
Done!
