### ISSUE TITLE
Fix links resulting in a 400 error on guides.18f.gov

### ISSUE THREAD

**Issue by juliaklindpaintner** [18F/guides#538]
### A description of the work

A sub-ticket of https://github.com/18F/guides/issues/531, this issue is to address the 400 errors identified by a scan of the guides.18f.gov website in March 2024. 

Anticipated tasks:
- [x] Filter [this spreadsheet](https://docs.google.com/spreadsheets/d/1KibtrzcBX-Qig1S2uawd3SHak9yfeG6toHpFU7VKKNs/edit#gid=0) in column H "Error code" by 400
- [x] Identify the bad link and look for a replacement
- [ ] If possible, replace. If not easily identified, recommend either removing or replacing with something similar.
- [ ] As you address the links, add your resolution in column A — either link to the PR for the fix or note why couldn't fix it.

### Point of contact on this issue

TLC co-leads

### Skills Needed

- [X] Any Human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### Acceptance Criteria

All links returning 400 have been replaced or removed.

**Comment by jasnakai** [comment]
Hello all and specifically @juliaklindpaintner . I have found the links associated with the 400 errors. They are links to Twitter but I am not getting a 400 error when clicking the links. Am I missing something? TY!

**Comment by juliaklindpaintner** [comment]
Huh! That's interesting. I will admit I certainly didn't check all these, so I think if it's working that's fine. I think you can safely close this, then. Thanks for checking!

**Comment by jasnakai** [comment]
Closing this out because the links are working.
