### ISSUE TITLE
Update UX Guide Research Plan Resource

### ISSUE THREAD

**Issue by bpdesigns** [18F/guides#549]
### A description of the work

- [x] Review Research Plan design crit [notes](https://docs.google.com/document/d/1yJP1hLZS0zaGBCu5GGF44_Oca331UX9T7O_rAe-SSIA/edit)
- [x] Review plan template-related content in the UX guide
- [x] Update the page content and template to reflect feedback and align
- [x] plain language review of template and page content

See background note for previous work this relates to. 

**Background**
The 18F Design team collectively reviewed the outcomes of #[291](https://github.com/18F/guides/issues/291) and evaluated next steps in #[506](https://github.com/18F/guides/issues/506).

### Point of contact on this issue

You can reach out to @bpdesigns, or @dluetger for context on what actually got done in #291.

### Skills Needed

- [ ] Any Human
- [X] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [x] No

### How much time do you anticipate this work taking?

1 week

### Acceptance Criteria

Updated research plan that incorporates feedback

**Next Steps** 
@bpdesigns will create another ticket for implementation into the guide
```[tasklist]
### Tasks
- [x] Update the content of the template [google doc](https://docs.google.com/document/d/1INHuOhjv4SB8tBEBqFnVSdtSL9rCjTczyL3FLOt3v-4/edit)
- [x] get approval from codeowner
- [x] make decision about timing of implementation (before, or with other research changes)
```

**Comment by claireb-gsa** [comment]
I updated the template for myself during RRB - will use that and the notes!

**Comment by claireb-gsa** [comment]
Editing is happening in this google doc: https://docs.google.com/document/d/1INHuOhjv4SB8tBEBqFnVSdtSL9rCjTczyL3FLOt3v-4/edit#heading=h.csdvu6hz6072

@bpdesigns I didn't quite finish in this increment, but I'd love to keep the ticket and work on it in my first full increment starting Tuesday.

**Comment by bpdesigns** [comment]
Sounds good! Thanks :)

**Comment by bpdesigns** [comment]
There are 3 versions of the same thing and none match - some strategic decisions to be made - @bpdesigns and @claireb-gsa will meet to discuss.

**Comment by claireb-gsa** [comment]
Updated the body of the ticket to reflect a more accurate scope, including updating content in the Plan section of the UX guide that describes how the template should be used.

**Comment by bpdesigns** [comment]
Thanks @claireb-gsa !

**Comment by claireb-gsa** [comment]
Coordinating the larger effort of this as a new project, created a readme: https://docs.google.com/document/d/1pAL6NclrEomX3mmcVBTYZFbk_ihE-6r6nHc2dHO6POg/edit

**Comment by claireb-gsa** [comment]
Have a draft of the template. Content and structure may change based on shifts to the research guide content, but this cleans up some current problems. 

[Research plan [Template] - NEW! ](https://docs.google.com/document/d/1INHuOhjv4SB8tBEBqFnVSdtSL9rCjTczyL3FLOt3v-4/edit#heading=h.4zcdxv2dxlcy) (should link to the header, but if not, look for the - NEW!)

**Comment by bpdesigns** [comment]
Thanks @claireb-gsa added some notes. Looks great!

**Comment by claireb-gsa** [comment]
working on comments, replying with questions

**Comment by claireb-gsa** [comment]
OK! @bpdesigns there is one section taht could use your further review - title and intro to the ethics/legal/bias stuff. https://docs.google.com/document/d/1INHuOhjv4SB8tBEBqFnVSdtSL9rCjTczyL3FLOt3v-4/edit#heading=h.5miay9jufeo0

**Comment by bpdesigns** [comment]
Reviewed!

**Comment by claireb-gsa** [comment]
Thank you @bpdesigns!  I'll touch base next week to get an implementation ticket started.

**Comment by bpdesigns** [comment]
@claireb-gsa Looks great! Added one comment in the doc for discussion.

**Comment by claireb-gsa** [comment]
Implementation ticket: https://github.com/18F/TLC-crew/issues/796

**Comment by bpdesigns** [comment]
LGTM! ✅

**Comment by claireb-gsa** [comment]
Merge complete!
