### ISSUE TITLE
[Request]: Update mentions of Path Analysis phase

### ISSUE THREAD

**Issue by nicoleslaw** [18F/guides#555]
### A description of the work

The UX Guide mentions the newly renamed phase of Path Analysis. I would recommend updating these references, for example: https://guides.18f.gov/ux-guide/our-approach/stay-lean/ 

This may also appear in other guides.

- [ ] Review guides for mentions of Path Analysis
- [ ] Update language and links as needed per BD

### Point of contact on this issue

BD representative (not sure!)

### Skills Needed

- [X] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

~1 day depending on Github proficiency

### Acceptance Criteria

- [ ] Mentions of path analysis are updated throughout the guides

**Comment by claireb-gsa** [comment]
I think there may be other mentions of project types and phases elsewhere in the guide, do they also need updating? https://18f.gsa.gov/work-with-us/

**Comment by nicoleslaw** [comment]
@claireb-gsa Yes! I had a task in the ticket to audit for all of the mentions.

**Comment by bpdesigns** [comment]
@adunkman prioritizing this as it is fixing outdated content on our website.

**Comment by amandacostello** [comment]
I propose this gets merged into #771 "work with us" web content since we're clarifying offering names there. I can take this on as part of that issue.

**Comment by adunkman** [comment]
As this gets moving, just a reminder that our named service offerings (Path Analysis, Strategy Development) are different than the execution of our approach (start with a discovery phase) — we haven’t always been consistent with this. 

Path Analysis -> Strategy Development makes sense for service offerings; Path Analysis -> Discovery makes sense for approaches. Happy to help disambiguate as needed!

**Comment by a-chappelear** [comment]
In the guides I only found 4 mentions of PA (one needed to be changed to discovery vs strat dev) Links are updated to [https://18f.gsa.gov/work-with-us/](https://18f.gsa.gov/work-with-us/) for strat dev (it was mentioned that the strat page may move and this was a safer option...)

[I created a PR, ](https://github.com/18F/guides/pull/661)where the changes can be reviewed.
