### ISSUE TITLE
New method card: Equity pause

### ISSUE THREAD

**Issue by allisonpress** [18F/guides#578]
Background
Our "fundamentals" section doesn't include anything about ethics or how we engage with participants.
This issue covers creating a card length overview of ethical considerations and how to engage with communities respectfully. This might actually warrant two cards( (1) Ethics; (2) Engaging with communities ), but TBD by whoever starts to work on this. Also, depending on the bandwidth of whoever picks this up, it could be broken down into a two phases/issues: one to draft the content and a second issue to implement the content.

A great starting point is a card version of the content here: https://docs.google.com/document/d/1yCmrmijLeaa-xEtONNiLl8ape_cVi5CNXEEjqNHtOSA/edit

**Acceptance criteria (we'll know we're done when…)**

-  Visitors can quickly learn about ethical considerations for their project, and how to discuss those as a team
-  A "fundamentals" card that covers ethics is live on the Methods site

**Timeline**
Does this need to happen in the next two weeks?

- [ ]  Yes
- [ ]  No

**How much time do you anticipate this work taking?**
Two weeks

**Tasks**
- [x] Review [Methods content vision](https://github.com/18F/methods/wiki) and [UX Guide content vision](https://github.com/18F/ux-guide/wiki)
- [x] Draft content in accordance with [this checklist](https://github.com/18F/methods/wiki/Content-editing-checklist#standard-method-pages), using [this template](https://docs.google.com/document/d/1gBNvcB-Wtn0xqiM1-yEhhfcdE6ghcI6UXjWSGg7l3Do/edit)
- [ ]  Peer review
- [ ]  Writing lab review
- [ ]  PO review
- [ ]  Accessibility review [if needed]

**Comment by allisonpress** [comment]
Here's a draft of the [equity pause method card content.](https://docs.google.com/document/d/1Hr6cZkydm0El6Ul7tQwmG4CtAHPC0kvRYB2z05M-FQ4/edit)
