### ISSUE TITLE
[Request]: Add recruiting roster template to the Recruiting method card

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#614]
### A description of the work

This issue is a continuation of https://github.com/18F/guides/issues/400.

We'd like to take this [recruiting roster template](https://docs.google.com/spreadsheets/d/1SHvm0DGo81jFV2JnsFe2l7YnNSmv29Xl59G4yeyknK4/edit#gid=0) and add it as a resource to the [Recruiting method card](https://guides.18f.gov/methods/fundamentals/recruiting/).

### Point of contact on this issue

@bpdesigns

### Skills Needed

- [X] Any Human
- [ ] Design
- [X] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

One week

### Acceptance Criteria

- [ ] Clean up the existing template
- [ ] Add context and instructions to the template
- [ ] Export it as a CSV
- [ ] Create an issue to host the CSV on the UX Guide
- [ ] Create a PR to host the CSV on the UX Guide
- [ ] Create an issue to link to the CSV on the [Recruiting](https://guides.18f.gov/methods/fundamentals/recruiting/) method card
- [ ] Create a PR to link to the CSV on the [Recruiting](https://guides.18f.gov/methods/fundamentals/recruiting/) method card

**Comment by peterrowland** [comment]
The  [interview roster template](https://docs.google.com/spreadsheets/d/1SHvm0DGo81jFV2JnsFe2l7YnNSmv29Xl59G4yeyknK4/edit#gid=0) is simple enough to be converted to CSV (except the Y/N drop down column) as it is. Instructions and context could be added above or below each header cell, but because CSV doesn't support formatting it may be confusing to users when they open the file. 

As with #616, it may be better to create an example PDF file that preserves formatting and includes context for how to use it, but that file would be a reference rather than a usable template.
