### ISSUE TITLE
[Request]: Add UX comparative analysis template to the Comparative analysis method card

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#615]
### A description of the work

This issue is a continuation of https://github.com/18F/guides/issues/400.

We'd like to take this [UX comparative analysis template](https://docs.google.com/spreadsheets/d/1hPuWrtqyUc6iSOlO9s9u7SRRKqDQkro5VZTgPcQHq-I/edit#gid=0) to the [Comparative analysis method card](https://guides.18f.gov/methods/decide/comparative-analysis/).

### Point of contact on this issue

@bpdesigns

### Skills Needed

- [ ] Any Human
- [X] Design
- [X] Content
- [X] Engineering
- [ ] Acquisition
- [X] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [ ] No

### How much time do you anticipate this work taking?

One week

### Acceptance Criteria

- [ ] Find examples of existing reviews people at 18F have done
- [ ] Figure out what format to share this template in (for example, PDF, CSV, or something else?)
- [ ] Create an issue to host the template file on the UX guide
- [ ] Create a PR to host the template file on the UX guide
- [ ] Create an issue to add a link to the hosted template to the [Comparative analysis](https://guides.18f.gov/methods/decide/comparative-analysis/) method card
- [ ] Create a PR to add a link to the hosted template to the [Comparative analysis](https://guides.18f.gov/methods/decide/comparative-analysis/) method card
