### ISSUE TITLE
[Request]: Add content inventory template to Content audit method card

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#616]
### A description of the work

his issue is a continuation of https://github.com/18F/guides/issues/400.

We'd like to add this [content inventory template](https://docs.google.com/spreadsheets/d/1BMFA0uodJoXUn4rP3w-tR0ttnaJGxm-jzWZdxT63xj0/edit#gid=701675758) to [Content audit method card](https://guides.18f.gov/methods/decide/content-audit/).

### Point of contact on this issue

@bpdesigns

### Skills Needed

- [X] Any Human
- [ ] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

1 week

### Acceptance Criteria

- [ ] Review the existing template for any updates or changes
- [ ] Export the existing template as a CSV
- [ ] Create an issue to host the CSV on the Content guide
- [ ] Create a PR to host the CSV on the Content guide
- [ ] Create an issue to link to the CSV on [Content audit](https://guides.18f.gov/methods/decide/content-audit/)
- [ ] Create a PR to link to the CSV on [Content audit](https://guides.18f.gov/methods/decide/content-audit/)

**Comment by peterrowland** [comment]
The [content inventory template](https://docs.google.com/spreadsheets/d/1BMFA0uodJoXUn4rP3w-tR0ttnaJGxm-jzWZdxT63xj0/edit#gid=701675758) is too complex to be converted to a CSV file because it has multiple sheets, drop down selection fields, and formatting that CSV files don't support.

It could be distributed as a PDF that preserves the design of this template and communicates to users how to use it, but in that format it would be an example rather than a file that someone could download and use.
