### ISSUE TITLE
[Request]: Determine whether the content strategy template should be added to the Content guide

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#620]
### A description of the work

This issue is a continuation of https://github.com/18F/guides/issues/400.

We have an internal content strategy template that could be nice to share externally on the [Content guide](https://guides.18f.gov/content-guide/our-approach/).

Tasks

- [ ] Determine if this is something we do want to share publicly
- [ ] Create an issue to make a new page for this template on the Content guide
- [ ] Create an issue to link to the new template page on the appropriate Content guide page

### Point of contact on this issue

@bpdesigns

### Skills Needed

- [ ] Any Human
- [ ] Design
- [X] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

One week

### Acceptance Criteria

- [ ] We have determined whether or not we want to share this template publicly
- [ ] If yes, the template is available on the Content guide

**Comment by bpdesigns** [comment]
@durland18F @amandacostello thoughts on this?
