### ISSUE TITLE
[Request]: Create a card sorting template we can share with the public

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#621]
### A description of the work

This issue is a continuation of https://github.com/18F/guides/issues/400.

### Tasks
- [x] Find existing card sorting templates (such as [this Mural template](https://app.mural.co/t/gsa6/m/gsa6/1616783457767/48f0878009965a36c806a4bcd803060897cde7e5?sender=ub220290cabe8bfe4d5383185)) and examples (such as [this project example](https://github.com/18F/C2/wiki/Sprint-5:-Interaction-model-June-2016))
- [x] Create new shareable template based on that research
  - [ ] Ensure the template is accessible
- [x] Create an issue to host this new template on the appropriate guide (UX or content?)
- [x] Create an issue to add a link to the template on the [card sort method card](https://guides.18f.gov/methods/validate/card-sorting/)

### Point of contact on this issue

@bpdesigns

### Skills Needed

- [X] Any Human
- [ ] Design
- [X] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

Two weeks

### Acceptance Criteria

- [x] We have a card sorting template we can share publicly
- [x] The template is hosted somewhere within our infrastructure
- [x] A link to the template has been added to the [card sort method card](https://guides.18f.gov/methods/validate/card-sorting/)

**Comment by janelx** [comment]
Notes and template [recommendations here](https://docs.google.com/document/d/1oEISUauG7uU6eP583yN_9Ia5nu-zRYW6uZvnT4FYJ-0/edit#heading=h.dr2uw1etpcq0).

**Comment by janelx** [comment]
[Google Doc template](https://docs.google.com/document/d/1Tk8Qx9i4TxPnEX7K_AbuxD0HoWXwBtYmDVnLOfFqpco/edit?usp=sharing) and [Figma Template](https://www.figma.com/board/jhPXgKic2ory6wWu27XcDj/18F-Card-Sort-Template?node-id=1-348&t=MpLc2QcZM10t2gLG-1)
