### ISSUE TITLE
[Request]: Make recommended changes in onboarding checklist for 18F tabs

### ISSUE THREAD

**Issue by mitogi** [18F/guides#634]
### A description of the work

The onboarding workgroup wants to follow up enact the recommendations synthesized from the [onboarding retro] (https://github.com/18F/TLC-crew/issues/742) ticket request.

Because we only have direct control over 18F tabs, this ticket only requests edits for 18F's tabs. 
Another ticket will be opened to compile recommendations for TTS onboarding.

### Point of contact on this issue

Christine Bath

### Reproduction steps (if necessary)

Update the 18F tab in the onboarding checklist with the updates below. Use the [Onboarding Cleanup list](https://docs.google.com/document/d/195Yc_NZfRoB4-_9uQRQhCtjiri1r_p4yoeEzpDQdkqQ/edit) and [18F onboarding retro synthesis](https://docs.google.com/document/d/1RUh-uwHBfrRFmv4dKE9VlEZIIUMH8yvnP_Apcn6i0-s/edit) to inform edits.

- [x] Address formatting so that the colors of To Do, Blocked, and Done appropriately change
- [ ] Review instructions and make sure there's no contradictory information upon clicking links to handbook
- [ ] Update 18F tab descriptions to provide more useful information

### Skills Needed

- [X] Any Human
- [ ] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

15-20 hours

### Acceptance Criteria

All issues identified in the [Onboarding Cleanup list](https://docs.google.com/document/d/195Yc_NZfRoB4-_9uQRQhCtjiri1r_p4yoeEzpDQdkqQ/edit) pertaining to the 18F onboarding tab are resolved or flagged as not resolved. Compile a list of any unresolved recommendations to share with Christine Bath.

**Comment by mitogi** [comment]
Progress so far (18F tab)
[Demo 18F tab](https://docs.google.com/spreadsheets/d/1poJv32M5wTnJ1x8JXsH46UPLgBVPqrSraZOLXMUaMLE/edit?gid=48926063#gid=48926063)

- Updated formatting for To Do, Completed, and Blocked
- Made notes to review with Christine

**Comment by mitogi** [comment]
Once I finish synthesis from [#635 ticket](https://github.com/18F/guides/issues/635), I can add more notes to the [Demo 18F tab](https://docs.google.com/spreadsheets/d/1poJv32M5wTnJ1x8JXsH46UPLgBVPqrSraZOLXMUaMLE/edit?gid=48926063#gid=48926063).

This should take 2-3 hours max, but it's bottlenecked by the synthesis work, which may take 4-7 hours.

**Comment by mitogi** [comment]
Changes have been made to the 18F new hire checklist!
