### ISSUE TITLE
[Request]: Experience Design for Onboarding Improvement

### ISSUE THREAD

**Issue by mitogi** [18F/guides#635]
### A description of the work

The onboarding workgroup wants to follow up enact the recommendations synthesized from the [onboarding retro] (https://github.com/18F/TLC-crew/issues/742) ticket request.

This ticket asks to use the [Onboarding Cleanup list](https://docs.google.com/document/d/195Yc_NZfRoB4-_9uQRQhCtjiri1r_p4yoeEzpDQdkqQ/edit) and [18F onboarding retro synthesis](https://docs.google.com/document/d/1RUh-uwHBfrRFmv4dKE9VlEZIIUMH8yvnP_Apcn6i0-s/edit) to create a "journey map" of the onboarding experience and outline next steps to address current gaps.

### Point of contact on this issue

Christine Bath

### Reproduction steps (if necessary)

- [x] Map out buddy, supervisor, and newhire journey.
- [x] Document analysis of resources / information that supervisors, onboarding buddies, and newhires get
- [x] Identify gaps in the journey and potential options to address them
- [x] Follow up interviews if clarification is needed
- [x] Create action plan for working group that: 

   - Highlights gaps in the process
   - Recommends concrete next steps
   - Prioritizes issues

Optional:
- [ ] Identify out-of-date information within onboarding process

### Skills Needed

- [ ] Any Human
- [X] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

30-35 hours

### Acceptance Criteria

The final deliverable should  

- [ ] Illustrate where gaps are in the onboarding experience
- [ ] Identify issues/recommendations in current artifacts used by newhires, supes, or onboarding buddies
- [ ] Prioritize issues/recommendations so that working group can organize the work ahead
- [ ] Articulate concrete action to address each gap identified
- [ ] Be a grounding framework to discuss future revamps of the onboarding process

**Comment by mitogi** [comment]
This is the progress so far
[Journey Maps](https://www.figma.com/board/hg2bS3Cau9dk3bNDoiUPUj/Onboarding-Journey-Map?node-id=0-1&t=geXjKtVcApQM4l0s-0)

**Comment by mitogi** [comment]
I need 4-7 hours to synthesize the interviews and write up recommendations.

**Comment by mitogi** [comment]
Talked with @cmajel about [Recommendations List for 18F.](https://docs.google.com/document/d/1y4oBRj70bTiqq_usCgl4EmS24eVb9v3ZuVRjLTzDL_k/edit)

We prioritized next steps and will work on those tasks in new tickets.
