### ISSUE TITLE
[Request]: Compile onboarding issues to communicate to TTS

### ISSUE THREAD

**Issue by mitogi** [18F/guides#636]
### A description of the work

The onboarding workgroup wants to follow up enact the recommendations synthesized from the [onboarding retro] (https://github.com/18F/TLC-crew/issues/742) ticket request.

This ticket asks to identify onboarding issues that need to be resolved by the larger TTS team (and potentially other departments) and compile them to share with TTS onboarding coordinators.

### Point of contact on this issue

Christine Bath

### Reproduction steps (if necessary)

Use the [Onboarding Cleanup list](https://docs.google.com/document/d/195Yc_NZfRoB4-_9uQRQhCtjiri1r_p4yoeEzpDQdkqQ/edit) and [18F onboarding retro synthesis](https://docs.google.com/document/d/1RUh-uwHBfrRFmv4dKE9VlEZIIUMH8yvnP_Apcn6i0-s/edit) to identify what issues are fall within TTS's scope. 

Additionally, identify issues that may fall under other departments' scope.

Create a report / presentation that
- [ ] Illustrate where gaps are in the onboarding experience
- [ ] Prioritize issues/recommendations 
- [ ] Provide suggestions to address each gap identified

### Skills Needed

- [ ] Any Human
- [X] Design
- [ ] Content
- [ ] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

15-20 hours

### Acceptance Criteria

The final deliverable should be a report / presentation that can Christine Bath can share to TTS.

**Comment by bpdesigns** [comment]
@adunkman for visibility this ticket along with #[634](https://github.com/18F/guides/issues/634) and  #[635](https://github.com/18F/guides/issues/635) is work for a working group, follow on work from previous work and is scoped for a specific member of TLC.

**Comment by mitogi** [comment]
This is the progress so far
https://docs.google.com/document/d/1948_6I-d6JK3TajalTRKK79gTkCqXRlvMS6K1Gc1cu0/edit

**Comment by mitogi** [comment]
The [notes to TTS is complete](https://docs.google.com/document/d/1948_6I-d6JK3TajalTRKK79gTkCqXRlvMS6K1Gc1cu0/edit#heading=h.evf5mg2exvrp).

Waiting on Christine to talk to Annabel about it. In Review.
Seylene from TTS is also interested in looking at the doc.

**Comment by mitogi** [comment]
We've given the [notes to TTS](https://docs.google.com/document/d/1948_6I-d6JK3TajalTRKK79gTkCqXRlvMS6K1Gc1cu0/edit#heading=h.evf5mg2exvrp).

Things are in their hands now.
