### ISSUE TITLE
[Request]: Improve responsiveness of tables

### ISSUE THREAD

**Issue by melchoyce** [18F/guides#712]
### A description of the work

Tables are not responsive on the Guides sites:

| Derisking | UX |
|--------|--------|
| ![IMG_0173](https://github.com/user-attachments/assets/6e34eade-b2a7-498f-ae4c-c6a6573da540) | ![IMG_0174](https://github.com/user-attachments/assets/b1522268-da18-47b2-a656-a947deeeddf9) | 

On mobile, the page allows for side scrolling, but smaller browser screens on desktop do not, so the content isn't accessible for non-assistive tech users.

We should improve the responsiveness of tables in the Guides sites by default.

### Skills Needed

- [ ] Any Human
- [X] Design
- [ ] Content
- [X] Engineering
- [ ] Acquisition
- [ ] Product
- [ ] Other

### Does this need to happen in the next 2 weeks?

- [ ] Yes
- [X] No

### How much time do you anticipate this work taking?

2 weeks

### Acceptance Criteria

- [ ] We have identified what kind of approach to responsive tables is best for the Guides content
- [ ] We've tested the approach to ensure it's accessible
- [ ] That approach has been coded and pushed up to the Guides

**Comment by edwintorres** [comment]
We don't have the tables any more.

**Comment by melchoyce** [comment]
Hey Edwin, we do still have tables in the Guides:

- https://guides.18f.gov/derisking-government-tech/resources/quality-indicators/
- https://guides.18f.gov/ux-guide/resources/research-plan/
